// auto-generated by export_data.py — 2026-06-24
window.REPORT_DATA = {
  "meta": {
    "dateRange": "1월 1일 ~ 6월 23일",
    "startDate": "2026-01-01",
    "endDate": "2026-06-23",
    "generatedAt": "2026-06-24 19:53",
    "curYear": 2026,
    "prevYear": 2025,
    "sources": {
      "cur": "고급모드->분석 데이터(2026)/콘텐츠 2026-01-01_2026-06-24 Giants TV",
      "prev": "과거 데이터/콘텐츠 2025-01-01_2025-06-22 Giants TV",
      "traffic": "고급모드->트래픽소스(2026)/트래픽 소스 2026-01-01_2026-06-24 Giants TV"
    }
  },
  "subscribers": {
    "lotte": {
      "name": "롯데",
      "subs": 378000,
      "delta": 0
    },
    "teams": [
      {
        "name": "한화",
        "subs": 561000,
        "delta": 0
      },
      {
        "name": "기아",
        "subs": 408000,
        "delta": 0
      },
      {
        "name": "삼성",
        "subs": 386000,
        "delta": 0
      },
      {
        "name": "롯데",
        "subs": 378000,
        "delta": 0
      },
      {
        "name": "lg",
        "subs": 329000,
        "delta": 0
      },
      {
        "name": "두산",
        "subs": 287000,
        "delta": 0
      },
      {
        "name": "ssg",
        "subs": 226000,
        "delta": 0
      },
      {
        "name": "NC",
        "subs": 131000,
        "delta": 0
      },
      {
        "name": "kt",
        "subs": 126000,
        "delta": 0
      },
      {
        "name": "키움",
        "subs": 124000,
        "delta": 0
      }
    ]
  },
  "counts": {
    "planned": {
      "cur": 94,
      "prev": 174
    },
    "fixed": {
      "cur": 328,
      "prev": 109
    },
    "semi": {
      "cur": 0,
      "prev": 2
    },
    "total": {
      "cur": 422,
      "prev": 285
    }
  },
  "planned": {
    "count": 94,
    "countPrev": 174,
    "avgViews": 84915,
    "avgViewsPrev": 128079,
    "totalViews": 7982038,
    "totalViewsPrev": 22285773,
    "watchTimeH": 358519,
    "watchTimeHPrev": 1501768,
    "avgDurFmt": "2분 19초",
    "avgDurFmtPrev": "2분 50초",
    "avgCTR": 5.96,
    "avgCTRPrev": 6.48,
    "totalSubs": 2598,
    "totalSubsPrev": 19375,
    "subConv": 32.5,
    "subConvPrev": 86.9,
    "newViewers": 0,
    "newViewersPrev": 0,
    "reVisitors": 0,
    "reVisitorsPrev": 0,
    "newViewersPct": 0.0,
    "newViewersPctPrev": 0.0
  },
  "fixed": {
    "count": 328,
    "countPrev": 109,
    "avgViews": 61817,
    "watchTimeH": 1296964
  },
  "hotdug": {
    "cur": {
      "label": "HOTDUG",
      "count": 29,
      "avgViews": 77409,
      "watchTimeH": 218894,
      "subs": 749,
      "avgCTR": 7.71,
      "avgViewRate": 48.6
    },
    "prev": {
      "label": "#플레이볼",
      "count": 16,
      "avgViews": 133592,
      "watchTimeH": 253063,
      "subs": 2230,
      "avgCTR": 8.9,
      "avgViewRate": 46.3
    }
  },
  "top10": [
    {
      "title": "DAY6 성진이 부르는 오늘도 승리한다🔥#DAY6 #성진 #롯데자이언츠 #응원가",
      "views": 438524,
      "ctr": 6.4,
      "tag": "콜라보"
    },
    {
      "title": "[주간 예열🔥] 예열을 위한 미리 듣는 롯데자이언츠 응원가 시리즈 | 영광의 순간 feat. 데이식스 성진",
      "views": 375441,
      "ctr": 6.9,
      "tag": "콜라보"
    },
    {
      "title": "DAY6 성진이 부르는 영광의 순간🔥",
      "views": 308630,
      "ctr": 6.2,
      "tag": "콜라보"
    },
    {
      "title": "[주간 예열🔥] 예열을 위한 미리 듣는 롯데자이언츠 응원가 시리즈 | 승리를 위한 전진 feat. 데이식스 성진",
      "views": 219026,
      "ctr": 6.6,
      "tag": "콜라보"
    },
    {
      "title": "[주간 예열🔥] 예열을 위한 미리 듣는 롯데자이언츠 응원가 시리즈 | 오늘도 승리한다 feat. 데이식스 성진",
      "views": 212844,
      "ctr": 6.7,
      "tag": "콜라보"
    },
    {
      "title": "[AIM HIGH] 청백전 1차전 in 타이난🔥 #하이라이트",
      "views": 168828,
      "ctr": 6.5,
      "tag": "기획"
    },
    {
      "title": "롯데자이언츠X세븐일레븐 띠부씰 맞히기 게임🫵 | 대환장 인물퀴즈까지!",
      "views": 161819,
      "ctr": 5.2,
      "tag": "기획"
    },
    {
      "title": "[AIM HIGH] 루키 박정민의 첫 등판부터 청백전 첫 홈런포까지🔥 l 청백전 2차전 #스프링캠프",
      "views": 160943,
      "ctr": 6.9,
      "tag": "기획"
    },
    {
      "title": "\"2026시즌, 더 높은 비상을 위한 준비. 지금, AIM HIGH.\"",
      "views": 160529,
      "ctr": 7.8,
      "tag": "기획"
    },
    {
      "title": "하늘마저 붙잡고 싶었던 마지막 인사 | 정훈의 이야기",
      "views": 156048,
      "ctr": 8.4,
      "tag": "기획"
    }
  ],
  "burst": {
    "count": 21,
    "shortsCount": 16,
    "longformCount": 5,
    "avgCTR": 7.9,
    "avgViews": 67469,
    "shortsAvgViews": 40108,
    "totalViews": 979079,
    "channelAvgCTR": 7.09,
    "channelAvgViews": 91648,
    "byDate": [
      {
        "date": "2026-06-21",
        "count": 7,
        "shortsCount": 4,
        "longformCount": 3,
        "avgCTR": 8.03,
        "avgViews": 73747
      },
      {
        "date": "2026-06-22",
        "count": 14,
        "shortsCount": 12,
        "longformCount": 2,
        "avgCTR": 7.69,
        "avgViews": 58052
      }
    ],
    "videos": [
      {
        "title": "정우의 엄청난 팬서비스 | 롯데! 한 다이 됐나! #롯데자이언츠 #정우",
        "views": 142754,
        "ctr": 5.8,
        "category": "기획",
        "is_shorts": true
      },
      {
        "title": "오랜만에 만난 DAY6 성진과 김원중 | 머리카락 근황 토크(?) #롯데자이언츠 #DAY6 #성진",
        "views": 94338,
        "ctr": 7.1,
        "category": "기획",
        "is_shorts": true
      },
      {
        "title": "[HIGHLIGHT] 롯데 VS 키움(06.21) | 한동희의 선취 적시타와 김동현의 쓰리런, 팀의 리드를 지켜낸 불펜진!🔥",
        "views": 88351,
        "ctr": 7.2,
        "category": "고정",
        "is_shorts": false
      },
      {
        "title": "팬들과 함께 | 끝까지 포기하지 마 (Return to Giants' home)",
        "views": 82228,
        "ctr": 9.6,
        "category": "기획",
        "is_shorts": false
      },
      {
        "title": "점수 차를 벌리는 김동현의 쓰리런🔥 #핫클립 #김동현",
        "views": 75230,
        "ctr": 6.7,
        "category": "고정",
        "is_shorts": true
      },
      {
        "title": "[HOTDUG] 김동현의 쓰리런, 윤동희 멀티히트 활약🔥(06.21)",
        "views": 68517,
        "ctr": 8.7,
        "category": "고정",
        "is_shorts": false
      },
      {
        "title": "승리의 하이파이브✋",
        "views": 63384,
        "ctr": 9.4,
        "category": "고정",
        "is_shorts": true
      },
      {
        "title": "[HOTDUG] 투타 완벽 조화로 완성한 승리🔥 (06.20)",
        "views": 50662,
        "ctr": 7.3,
        "category": "고정",
        "is_shorts": false
      },
      {
        "title": "김원중이 가르쳐주는 슬라이더 | 시구자 최초(?) 변화구 시도? #롯데자이언츠 #DAY6 #성진",
        "views": 48187,
        "ctr": 6.9,
        "category": "기획",
        "is_shorts": true
      },
      {
        "title": "[전지적 동현 시점] 김동현이 들려주는 첫 안타, 첫 홈런 이야기✨",
        "views": 47586,
        "ctr": 6.7,
        "category": "기획",
        "is_shorts": false
      },
      {
        "title": "선취점을 얻어내는 한동희의 적시타🔥 #핫클립 #한동희",
        "views": 32016,
        "ctr": 3.0,
        "category": "고정",
        "is_shorts": true
      },
      {
        "title": "요리로 따지자면? | 윤남노다운 시구 소감✨ #롯데자이언츠 #윤남노",
        "views": 23603,
        "ctr": 2.4,
        "category": "기획",
        "is_shorts": true
      },
      {
        "title": "최준용의 시구 지도 소감 | 짱구야! 한 다이 됐나! #롯데자이언츠",
        "views": 22495,
        "ctr": 5.4,
        "category": "기획",
        "is_shorts": true
      },
      {
        "title": "공이랑 낯가리는 윤남노💦⚾️ (feat. 시구 지도 선생님 김진욱) #롯데자이언츠 #윤남노",
        "views": 22370,
        "ctr": 4.9,
        "category": "기획",
        "is_shorts": true
      },
      {
        "title": "시구 전 토크 | 윤남노가 등번호 11번을 한 이유? #롯데자이언츠 #윤남노",
        "views": 21833,
        "ctr": 4.8,
        "category": "기획",
        "is_shorts": true
      },
      {
        "title": "DAY6 성진과 함께하는 롯데자이언츠 아웃송 메들리🎵 #롯데자이언츠 #DAY6 #성진",
        "views": 21396,
        "ctr": 5.1,
        "category": "기획",
        "is_shorts": true
      },
      {
        "title": "궁금한 게 많은 정우의 시구 연습⚾️ with 시구 지도 선생님 최준용 #롯데자이언츠 #정우",
        "views": 19896,
        "ctr": 4.0,
        "category": "기획",
        "is_shorts": true
      },
      {
        "title": "파이팅 넘치는 정우의 시구 소감✨ #롯데자이언츠 #정우",
        "views": 18831,
        "ctr": 4.0,
        "category": "기획",
        "is_shorts": true
      },
      {
        "title": "LINEUP\n6월 21일 (일) vs 키움\n선발 라인업을 공개합니다🔥\n\n등록: -\n말소: -",
        "views": 12528,
        "ctr": 0.0,
        "category": "고정",
        "is_shorts": true
      },
      {
        "title": "DAY6 성진이 라이브로 부르는 영광의 순간✨ #롯데자이언츠 #DAY6 #성진",
        "views": 11782,
        "ctr": 4.6,
        "category": "기획",
        "is_shorts": true
      },
      {
        "title": "칭찬만 가득한 시구 연습 현장✨ with 시구 경력 만렙 성진 #롯데자이언츠 #DAY6 #성진",
        "views": 11092,
        "ctr": 3.5,
        "category": "기획",
        "is_shorts": true
      }
    ]
  },
  "timing": {
    "uploadVsImpr": [
      {
        "uploadCount": 1,
        "days": 28,
        "videoCount": 28,
        "avgImpr": 940104,
        "avgViews": 79347
      },
      {
        "uploadCount": 2,
        "days": 16,
        "videoCount": 32,
        "avgImpr": 989894,
        "avgViews": 86688
      },
      {
        "uploadCount": 3,
        "days": 11,
        "videoCount": 33,
        "avgImpr": 937691,
        "avgViews": 86288
      },
      {
        "uploadCount": 4,
        "days": 5,
        "videoCount": 20,
        "avgImpr": 816779,
        "avgViews": 73256
      },
      {
        "uploadCount": 5,
        "days": 1,
        "videoCount": 5,
        "avgImpr": 325206,
        "avgViews": 34176
      }
    ],
    "timelinessHL": [
      {
        "label": "D+0",
        "count": 29,
        "avgViews": 120790,
        "avgImpr": 1474960,
        "avgCTR": 6.81
      },
      {
        "label": "D+1",
        "count": 1,
        "avgViews": 57503,
        "avgImpr": 897031,
        "avgCTR": 5.22
      }
    ]
  },
  "contentTypeConv": {
    "typeStats": [
      {
        "type": "생중계",
        "count": 8,
        "conv": 73.9,
        "avgViews": 12294,
        "avgCTR": 3.6,
        "avgSubs": 6.8
      },
      {
        "type": "예능",
        "count": 2,
        "conv": 61.3,
        "avgViews": 150894,
        "avgCTR": 5.8,
        "avgSubs": 93.5
      },
      {
        "type": "전지훈련",
        "count": 10,
        "conv": 43.5,
        "avgViews": 132015,
        "avgCTR": 7.0,
        "avgSubs": 57.7
      },
      {
        "type": "기타기획",
        "count": 20,
        "conv": 35.5,
        "avgViews": 82055,
        "avgCTR": 6.9,
        "avgSubs": 31.7
      },
      {
        "type": "공식행사",
        "count": 5,
        "conv": 29.4,
        "avgViews": 97106,
        "avgCTR": 6.3,
        "avgSubs": 32.8
      },
      {
        "type": "화보",
        "count": 3,
        "conv": 27.6,
        "avgViews": 86113,
        "avgCTR": 6.2,
        "avgSubs": 24.7
      },
      {
        "type": "인터뷰/예고",
        "count": 2,
        "conv": 23.9,
        "avgViews": 78457,
        "avgCTR": 6.9,
        "avgSubs": 19.0
      }
    ],
    "catCompare": [
      {
        "label": "기획 롱폼",
        "count": 52,
        "conv": 42.3,
        "avgViews": 86145,
        "totalSubs": 1797
      },
      {
        "label": "기획 숏츠",
        "count": 42,
        "conv": 13.3,
        "avgViews": 83393,
        "totalSubs": 801
      },
      {
        "label": "고정 롱폼",
        "count": 109,
        "conv": 47.4,
        "avgViews": 93165,
        "totalSubs": 5164
      }
    ]
  },
  "direction": [
    {
      "label": "감성/브랜딩형",
      "count": 42,
      "shortsCount": 24,
      "longformCount": 18,
      "avgViews": 125083,
      "avgCTR": 7.4,
      "avgImpr": 749505,
      "conv": 30.3,
      "convLongform": 47.5,
      "avgNewViewerPct": 4.4,
      "avgShares": 110,
      "avgLikes": 336,
      "avgRPM": 1586,
      "videos": [
        {
          "title": "DAY6 성진이 부르는 오늘도 승리한다🔥#DAY6 #성진 #롯데자이언츠 #응원가",
          "date": "03/13",
          "views": 438524,
          "ctr": 6.39,
          "conv": 13.5,
          "isShorts": true,
          "newViewerPct": 9.7,
          "shares": 139,
          "likes": 525,
          "rpm": 318
        },
        {
          "title": "[주간 예열🔥] 예열을 위한 미리 듣는 롯데자이언츠 응원가 시리즈 | 영광의 순간 feat. 데이식스 성진",
          "date": "03/14",
          "views": 375441,
          "ctr": 6.88,
          "conv": 47.9,
          "isShorts": true,
          "newViewerPct": 18.6,
          "shares": 1185,
          "likes": 1249,
          "rpm": 1375
        },
        {
          "title": "[미야자키 연습경기 생중계] vs 세이부라이온즈(2/22)",
          "date": "02/22",
          "views": 371114,
          "ctr": 15.71,
          "conv": 109.1,
          "isShorts": false,
          "newViewerPct": 9.7,
          "shares": 6,
          "likes": -27,
          "rpm": 0
        },
        {
          "title": "DAY6 성진이 부르는 영광의 순간🔥",
          "date": "03/14",
          "views": 308630,
          "ctr": 6.21,
          "conv": 6.8,
          "isShorts": true,
          "newViewerPct": 3.5,
          "shares": 47,
          "likes": 431,
          "rpm": 308
        },
        {
          "title": "[미야자키 구춘리그] vs 지바롯데마린스 (3/1)",
          "date": "03/01",
          "views": 292968,
          "ctr": 14.08,
          "conv": 75.1,
          "isShorts": false,
          "newViewerPct": 8.5,
          "shares": 3,
          "likes": -15,
          "rpm": 0
        },
        {
          "title": "[미야자키 연습경기] vs SSG (3/3)",
          "date": "03/03",
          "views": 245924,
          "ctr": 14.92,
          "conv": 95.2,
          "isShorts": false,
          "newViewerPct": 5.7,
          "shares": 6,
          "likes": -8,
          "rpm": 10162
        },
        {
          "title": "[미야자키 연습경기 생중계] vs 요미우리자이언츠(2/23)",
          "date": "02/23",
          "views": 236768,
          "ctr": 15.89,
          "conv": 68.4,
          "isShorts": false,
          "newViewerPct": 10.5,
          "shares": 3,
          "likes": -7,
          "rpm": 4906
        },
        {
          "title": "[미야자키 구춘리그] vs 두산베어스(2/26)",
          "date": "02/26",
          "views": 228065,
          "ctr": 15.92,
          "conv": 53.1,
          "isShorts": false,
          "newViewerPct": 9.2,
          "shares": 0,
          "likes": -11,
          "rpm": 1341
        },
        {
          "title": "[주간 예열🔥] 예열을 위한 미리 듣는 롯데자이언츠 응원가 시리즈 | 승리를 위한 전진 feat. 데이식스 성진",
          "date": "03/13",
          "views": 219026,
          "ctr": 6.63,
          "conv": 46.1,
          "isShorts": true,
          "newViewerPct": 6.0,
          "shares": 523,
          "likes": 574,
          "rpm": 1336
        },
        {
          "title": "[미야자키 구춘리그] 빗속을 가르는 두 개의 홈런포🔥 #김민성 #레이예스",
          "date": "02/26",
          "views": 214875,
          "ctr": 8.5,
          "conv": 7.4,
          "isShorts": true,
          "newViewerPct": 1.4,
          "shares": 0,
          "likes": -7,
          "rpm": 348
        }
      ]
    },
    {
      "label": "예능/참여형",
      "count": 22,
      "shortsCount": 4,
      "longformCount": 18,
      "avgViews": 91915,
      "avgCTR": 6.5,
      "avgImpr": 975465,
      "conv": 27.4,
      "convLongform": 32.7,
      "avgNewViewerPct": 1.3,
      "avgShares": 253,
      "avgLikes": 1507,
      "avgRPM": 1545,
      "videos": [
        {
          "title": "하늘마저 붙잡고 싶었던 마지막 인사 | 정훈의 이야기",
          "date": "04/18",
          "views": 156048,
          "ctr": 8.43,
          "conv": 26.9,
          "isShorts": false,
          "newViewerPct": 2.6,
          "shares": 752,
          "likes": 4989,
          "rpm": 1770
        },
        {
          "title": "등장곡 바꿀 선수는 여기로 오세요!✨ 2026 시즌 등장곡 드래프트",
          "date": "03/24",
          "views": 152440,
          "ctr": 6.19,
          "conv": 42.6,
          "isShorts": false,
          "newViewerPct": 1.2,
          "shares": 75,
          "likes": 463,
          "rpm": 0
        },
        {
          "title": "비시즌에 뭐 했어요? #롯데자이언츠",
          "date": "01/28",
          "views": 144143,
          "ctr": 7.44,
          "conv": 38.2,
          "isShorts": false,
          "newViewerPct": 0.4,
          "shares": 7,
          "likes": 127,
          "rpm": 0
        },
        {
          "title": "사직야구장 신메뉴 먹방 3코스 | 직관가서 뭐 먹지?🤔",
          "date": "04/29",
          "views": 139969,
          "ctr": 6.44,
          "conv": 52.2,
          "isShorts": false,
          "newViewerPct": 2.1,
          "shares": 1530,
          "likes": 2898,
          "rpm": 2722
        },
        {
          "title": "화이트데이 특집 | 먹을 수만 있게 만들어라 흑백두쫀쿠👩‍🍳🧆",
          "date": "03/14",
          "views": 119734,
          "ctr": 5.38,
          "conv": 41.8,
          "isShorts": false,
          "newViewerPct": 4.7,
          "shares": 44,
          "likes": 260,
          "rpm": 2347
        },
        {
          "title": "한태양의 NEW 응원가 공개🎶(with 윤동희, 이호준)",
          "date": "03/25",
          "views": 112718,
          "ctr": 9.84,
          "conv": 31.1,
          "isShorts": false,
          "newViewerPct": 2.9,
          "shares": 128,
          "likes": 352,
          "rpm": 1763
        },
        {
          "title": "건강한 복귀와 첫 승리!✨ 1승이 간절했던 순간들 l 주간 이슈",
          "date": "04/15",
          "views": 108989,
          "ctr": 7.07,
          "conv": 27.5,
          "isShorts": false,
          "newViewerPct": 1.0,
          "shares": 170,
          "likes": 3118,
          "rpm": 2322
        },
        {
          "title": "전지훈련 비행 브이로그 ✈️ | with 이스타항공, 그런데 이제.. 롯데고사를 곁들인",
          "date": "02/04",
          "views": 104642,
          "ctr": 7.63,
          "conv": 32.5,
          "isShorts": false,
          "newViewerPct": 0.5,
          "shares": 10,
          "likes": 123,
          "rpm": 0
        },
        {
          "title": "팬 여러분, 엘빈 선수 등장곡을 추천해 주세요!🎵",
          "date": "03/24",
          "views": 104485,
          "ctr": 6.18,
          "conv": 4.8,
          "isShorts": true,
          "newViewerPct": 0.5,
          "shares": 3,
          "likes": 322,
          "rpm": 319
        },
        {
          "title": "“와… 멋있는데?✨” 비주얼 대폭발한 프로필 촬영 현장! [1편] #프로필촬영 #비하인드",
          "date": "01/31",
          "views": 104295,
          "ctr": 5.88,
          "conv": 35.5,
          "isShorts": false,
          "newViewerPct": 0.2,
          "shares": 9,
          "likes": 75,
          "rpm": 2569
        }
      ]
    }
  ],
  "traffic": {
    "cur": {
      "label": "2026 1~6월",
      "data": [
        {
          "source": "탐색 기능",
          "views": 11329161,
          "ctr": 8.34,
          "pct": 40.1
        },
        {
          "source": "Shorts 피드",
          "views": 8272458,
          "ctr": 0.0,
          "pct": 29.3
        },
        {
          "source": "추천 동영상",
          "views": 2389275,
          "ctr": 4.52,
          "pct": 8.5
        },
        {
          "source": "채널 페이지",
          "views": 2335270,
          "ctr": 5.0,
          "pct": 8.3
        },
        {
          "source": "YouTube 검색",
          "views": 2013424,
          "ctr": 7.7,
          "pct": 7.1
        },
        {
          "source": "알림",
          "views": 552039,
          "ctr": 0.0,
          "pct": 2.0
        },
        {
          "source": "외부",
          "views": 332097,
          "ctr": 0.0,
          "pct": 1.2
        },
        {
          "source": "직접 입력 또는 알 수 없음",
          "views": 329014,
          "ctr": 0.0,
          "pct": 1.2
        },
        {
          "source": "기타 YouTube 기능",
          "views": 302291,
          "ctr": 0.0,
          "pct": 1.1
        },
        {
          "source": "재생목록",
          "views": 296430,
          "ctr": 5.39,
          "pct": 1.0
        },
        {
          "source": "최종 화면",
          "views": 89553,
          "ctr": 0.0,
          "pct": 0.3
        },
        {
          "source": "관련 Shorts 동영상",
          "views": 8928,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "세로형 실시간 피드",
          "views": 4704,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "해시태그 페이지",
          "views": 1616,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "사운드 페이지",
          "views": 858,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "리믹스 동영상",
          "views": 5,
          "ctr": 0.0,
          "pct": 0.0
        }
      ]
    },
    "prev": {
      "label": "2025 1~6월",
      "data": [
        {
          "source": "탐색 기능",
          "views": 13581662,
          "ctr": 8.38,
          "pct": 41.6
        },
        {
          "source": "Shorts 피드",
          "views": 6987605,
          "ctr": 0.0,
          "pct": 21.4
        },
        {
          "source": "채널 페이지",
          "views": 3629758,
          "ctr": 4.82,
          "pct": 11.1
        },
        {
          "source": "추천 동영상",
          "views": 3113227,
          "ctr": 4.02,
          "pct": 9.5
        },
        {
          "source": "YouTube 검색",
          "views": 3052496,
          "ctr": 8.53,
          "pct": 9.3
        },
        {
          "source": "알림",
          "views": 618318,
          "ctr": 0.0,
          "pct": 1.9
        },
        {
          "source": "외부",
          "views": 423669,
          "ctr": 0.0,
          "pct": 1.3
        },
        {
          "source": "기타 YouTube 기능",
          "views": 401707,
          "ctr": 0.0,
          "pct": 1.2
        },
        {
          "source": "직접 입력 또는 알 수 없음",
          "views": 375822,
          "ctr": 0.0,
          "pct": 1.2
        },
        {
          "source": "최종 화면",
          "views": 359154,
          "ctr": 0.0,
          "pct": 1.1
        },
        {
          "source": "재생목록",
          "views": 61820,
          "ctr": 6.29,
          "pct": 0.2
        },
        {
          "source": "관련 Shorts 동영상",
          "views": 30539,
          "ctr": 0.0,
          "pct": 0.1
        },
        {
          "source": "세로형 실시간 피드",
          "views": 25908,
          "ctr": 0.0,
          "pct": 0.1
        },
        {
          "source": "해시태그 페이지",
          "views": 4623,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "사운드 페이지",
          "views": 717,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "동영상 카드 및 특수효과",
          "views": 207,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "리믹스 동영상",
          "views": 10,
          "ctr": 0.0,
          "pct": 0.0
        }
      ]
    }
  },
  "daily": {
    "ctr": [],
    "likes": []
  }
};
