// auto-generated by export_data.py — 2026-06-23
window.REPORT_DATA = {
  "meta": {
    "dateRange": "1월 1일 ~ 6월 21일",
    "startDate": "2026-01-01",
    "endDate": "2026-06-21",
    "generatedAt": "2026-06-23 18:00",
    "curYear": 2026,
    "prevYear": 2025,
    "sources": {
      "cur": "고급모드->분석 데이터(2026)/콘텐츠 2026-01-01_2026-06-22 Giants TV",
      "prev": "과거 데이터/콘텐츠 2025-01-01_2025-06-22 Giants TV",
      "traffic": "고급모드->트래픽소스(2026)/트래픽 소스 2026-01-01_2026-06-22 Giants TV"
    }
  },
  "subscribers": {
    "lotte": {
      "name": "롯데",
      "subs": 377000,
      "delta": 377000
    },
    "teams": [
      {
        "name": "한화",
        "subs": 560000,
        "delta": 560000
      },
      {
        "name": "기아",
        "subs": 407000,
        "delta": 407000
      },
      {
        "name": "삼성",
        "subs": 386000,
        "delta": 386000
      },
      {
        "name": "롯데",
        "subs": 377000,
        "delta": 377000
      },
      {
        "name": "lg",
        "subs": 329000,
        "delta": 329000
      },
      {
        "name": "두산",
        "subs": 287000,
        "delta": 287000
      },
      {
        "name": "ssg",
        "subs": 225000,
        "delta": 225000
      },
      {
        "name": "NC",
        "subs": 131000,
        "delta": 131000
      },
      {
        "name": "kt",
        "subs": 126000,
        "delta": 126000
      },
      {
        "name": "키움",
        "subs": 124000,
        "delta": 124000
      }
    ]
  },
  "counts": {
    "planned": {
      "cur": 108,
      "prev": 177
    },
    "fixed": {
      "cur": 290,
      "prev": 106
    },
    "semi": {
      "cur": 0,
      "prev": 2
    },
    "total": {
      "cur": 398,
      "prev": 285
    }
  },
  "planned": {
    "count": 108,
    "countPrev": 177,
    "avgViews": 102334,
    "avgViewsPrev": 130660,
    "totalViews": 11052043,
    "totalViewsPrev": 23126782,
    "watchTimeH": 786429,
    "watchTimeHPrev": 1604910,
    "avgDurFmt": "3분 07초",
    "avgDurFmtPrev": "2분 54초",
    "avgCTR": 6.74,
    "avgCTRPrev": 6.48,
    "totalSubs": 4565,
    "totalSubsPrev": 21657,
    "subConv": 41.3,
    "subConvPrev": 93.6,
    "newViewers": 0,
    "newViewersPrev": 0,
    "reVisitors": 0,
    "reVisitorsPrev": 0,
    "newViewersPct": 0.0,
    "newViewersPctPrev": 0.0
  },
  "fixed": {
    "count": 290,
    "countPrev": 106,
    "avgViews": 55271,
    "watchTimeH": 825561
  },
  "hotdug": {
    "cur": {
      "label": "HOTDUG",
      "count": 28,
      "avgViews": 77255,
      "watchTimeH": 210522,
      "subs": 720,
      "avgCTR": 7.76,
      "avgViewRate": 48.5
    },
    "prev": {
      "label": "#플레이볼",
      "count": 16,
      "avgViews": 133592,
      "watchTimeH": 253063,
      "subs": 2230,
      "avgCTR": 8.9,
      "avgViewRate": 46.3
    }
  },
  "top10": [
    {
      "title": "DAY6 성진이 부르는 오늘도 승리한다🔥#DAY6 #성진 #롯데자이언츠 #응원가",
      "views": 438164,
      "ctr": 6.4,
      "tag": "콜라보"
    },
    {
      "title": "[미야자키 연습경기 생중계] vs 세이부라이온즈(2/22)",
      "views": 371101,
      "ctr": 15.7,
      "tag": "생중계"
    },
    {
      "title": "[주간 예열🔥] 예열을 위한 미리 듣는 롯데자이언츠 응원가 시리즈 | 영광의 순간 feat. 데이식스 성진",
      "views": 369804,
      "ctr": 6.9,
      "tag": "콜라보"
    },
    {
      "title": "[Playlist] 2026 롯데자이언츠 팀 응원가 + 신규 응원가 포함! #직관전필수시청",
      "views": 324750,
      "ctr": 8.1,
      "tag": "기획"
    },
    {
      "title": "DAY6 성진이 부르는 영광의 순간🔥",
      "views": 308443,
      "ctr": 6.2,
      "tag": "콜라보"
    },
    {
      "title": "[미야자키 구춘리그] vs 지바롯데마린스 (3/1)",
      "views": 292937,
      "ctr": 14.1,
      "tag": "생중계"
    },
    {
      "title": "[Playlist] 야수 등장곡+응원가 안무 버전✨ #직관전필수시청",
      "views": 252153,
      "ctr": 7.4,
      "tag": "기획"
    },
    {
      "title": "[미야자키 연습경기] vs SSG (3/3)",
      "views": 245915,
      "ctr": 14.9,
      "tag": "생중계"
    },
    {
      "title": "[미야자키 연습경기 생중계] vs 요미우리자이언츠(2/23)",
      "views": 236766,
      "ctr": 15.9,
      "tag": "생중계"
    },
    {
      "title": "[미야자키 구춘리그] vs 두산베어스(2/26)",
      "views": 228063,
      "ctr": 15.9,
      "tag": "생중계"
    }
  ],
  "burst": {
    "count": 7,
    "avgCTR": 6.86,
    "avgViews": 50291,
    "totalViews": 352040,
    "channelAvgCTR": 5.4,
    "channelAvgViews": 68360,
    "byDate": [
      {
        "date": "2026-06-21",
        "count": 7,
        "avgCTR": 6.86,
        "avgViews": 50291
      }
    ],
    "videos": [
      {
        "title": "[HIGHLIGHT] 롯데 VS 키움(06.21) | 한동희의 선취 적시타와 김동현의 쓰리런, 팀의 리드를 지켜낸 불펜진!🔥",
        "views": 82863,
        "ctr": 8.0,
        "category": "고정"
      },
      {
        "title": "팬들과 함께 | 끝까지 포기하지 마 (Return to Giants' home)",
        "views": 67570,
        "ctr": 10.7,
        "category": "기획"
      },
      {
        "title": "점수 차를 벌리는 김동현의 쓰리런🔥 #핫클립 #김동현",
        "views": 60240,
        "ctr": 7.4,
        "category": "고정"
      },
      {
        "title": "승리의 하이파이브✋",
        "views": 58832,
        "ctr": 10.0,
        "category": "고정"
      },
      {
        "title": "[HOTDUG] 투타 완벽 조화로 완성한 승리🔥 (06.20)",
        "views": 46365,
        "ctr": 8.2,
        "category": "고정"
      },
      {
        "title": "선취점을 얻어내는 한동희의 적시타🔥 #핫클립 #한동희",
        "views": 27551,
        "ctr": 3.7,
        "category": "고정"
      },
      {
        "title": "LINEUP\n6월 21일 (일) vs 키움\n선발 라인업을 공개합니다🔥\n\n등록: -\n말소: -",
        "views": 8619,
        "ctr": 0.0,
        "category": "고정"
      }
    ]
  },
  "traffic": {
    "cur": {
      "label": "2026 1~6월",
      "data": [
        {
          "source": "탐색 기능",
          "views": 11055680,
          "ctr": 8.36,
          "pct": 40.6
        },
        {
          "source": "Shorts 피드",
          "views": 7817194,
          "ctr": 0.0,
          "pct": 28.7
        },
        {
          "source": "추천 동영상",
          "views": 2305401,
          "ctr": 4.52,
          "pct": 8.5
        },
        {
          "source": "채널 페이지",
          "views": 2216333,
          "ctr": 5.02,
          "pct": 8.1
        },
        {
          "source": "YouTube 검색",
          "views": 1946895,
          "ctr": 7.76,
          "pct": 7.2
        },
        {
          "source": "알림",
          "views": 530189,
          "ctr": 0.0,
          "pct": 1.9
        },
        {
          "source": "직접 입력 또는 알 수 없음",
          "views": 324404,
          "ctr": 0.0,
          "pct": 1.2
        },
        {
          "source": "외부",
          "views": 324215,
          "ctr": 0.0,
          "pct": 1.2
        },
        {
          "source": "기타 YouTube 기능",
          "views": 291720,
          "ctr": 0.0,
          "pct": 1.1
        },
        {
          "source": "재생목록",
          "views": 289358,
          "ctr": 5.43,
          "pct": 1.1
        },
        {
          "source": "최종 화면",
          "views": 89062,
          "ctr": 0.0,
          "pct": 0.3
        },
        {
          "source": "관련 Shorts 동영상",
          "views": 8918,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "세로형 실시간 피드",
          "views": 4630,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "해시태그 페이지",
          "views": 1581,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "사운드 페이지",
          "views": 812,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "리믹스 동영상",
          "views": 5,
          "ctr": 0.0,
          "pct": 0.0
        }
      ]
    },
    "prev": {
      "label": "2025 1~6월",
      "data": [
        {
          "source": "탐색 기능",
          "views": 13581662,
          "ctr": 8.38,
          "pct": 41.6
        },
        {
          "source": "Shorts 피드",
          "views": 6987605,
          "ctr": 0.0,
          "pct": 21.4
        },
        {
          "source": "채널 페이지",
          "views": 3629758,
          "ctr": 4.82,
          "pct": 11.1
        },
        {
          "source": "추천 동영상",
          "views": 3113227,
          "ctr": 4.02,
          "pct": 9.5
        },
        {
          "source": "YouTube 검색",
          "views": 3052496,
          "ctr": 8.53,
          "pct": 9.3
        },
        {
          "source": "알림",
          "views": 618318,
          "ctr": 0.0,
          "pct": 1.9
        },
        {
          "source": "외부",
          "views": 423669,
          "ctr": 0.0,
          "pct": 1.3
        },
        {
          "source": "기타 YouTube 기능",
          "views": 401707,
          "ctr": 0.0,
          "pct": 1.2
        },
        {
          "source": "직접 입력 또는 알 수 없음",
          "views": 375822,
          "ctr": 0.0,
          "pct": 1.2
        },
        {
          "source": "최종 화면",
          "views": 359154,
          "ctr": 0.0,
          "pct": 1.1
        },
        {
          "source": "재생목록",
          "views": 61820,
          "ctr": 6.29,
          "pct": 0.2
        },
        {
          "source": "관련 Shorts 동영상",
          "views": 30539,
          "ctr": 0.0,
          "pct": 0.1
        },
        {
          "source": "세로형 실시간 피드",
          "views": 25908,
          "ctr": 0.0,
          "pct": 0.1
        },
        {
          "source": "해시태그 페이지",
          "views": 4623,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "사운드 페이지",
          "views": 717,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "동영상 카드 및 특수효과",
          "views": 207,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "리믹스 동영상",
          "views": 10,
          "ctr": 0.0,
          "pct": 0.0
        }
      ]
    }
  },
  "daily": {
    "ctr": [],
    "likes": []
  }
};
