// auto-generated by export_data.py — 2026-06-25
window.REPORT_DATA = {
  "meta": {
    "dateRange": "1월 1일 ~ 6월 23일",
    "startDate": "2026-01-01",
    "endDate": "2026-06-23",
    "generatedAt": "2026-06-25 12:24",
    "curYear": 2026,
    "prevYear": 2025,
    "sources": {
      "cur": "고급모드->분석 데이터(2026)/콘텐츠 2026-01-01_2026-06-24 Giants TV",
      "prev": "과거 데이터/콘텐츠 2025-01-01_2025-06-22 Giants TV",
      "traffic": "고급모드->트래픽소스(2026)/트래픽 소스 2026-01-01_2026-06-24 Giants TV"
    }
  },
  "subscribers": {
    "lotte": {
      "name": "롯데",
      "subs": 378000,
      "delta": 0
    },
    "teams": [
      {
        "name": "한화",
        "subs": 561000,
        "delta": 0
      },
      {
        "name": "기아",
        "subs": 408000,
        "delta": 0
      },
      {
        "name": "삼성",
        "subs": 386000,
        "delta": 0
      },
      {
        "name": "롯데",
        "subs": 378000,
        "delta": 0
      },
      {
        "name": "lg",
        "subs": 329000,
        "delta": 0
      },
      {
        "name": "두산",
        "subs": 287000,
        "delta": 0
      },
      {
        "name": "ssg",
        "subs": 226000,
        "delta": 0
      },
      {
        "name": "NC",
        "subs": 131000,
        "delta": 0
      },
      {
        "name": "kt",
        "subs": 126000,
        "delta": 0
      },
      {
        "name": "키움",
        "subs": 124000,
        "delta": 0
      }
    ]
  },
  "counts": {
    "planned": {
      "cur": 94,
      "prev": 174
    },
    "fixed": {
      "cur": 328,
      "prev": 109
    },
    "semi": {
      "cur": 0,
      "prev": 2
    },
    "total": {
      "cur": 422,
      "prev": 285
    }
  },
  "planned": {
    "count": 94,
    "countPrev": 174,
    "avgViews": 84915,
    "avgViewsPrev": 128079,
    "totalViews": 7982038,
    "totalViewsPrev": 22285773,
    "watchTimeH": 358519,
    "watchTimeHPrev": 1501768,
    "avgDurFmt": "2분 19초",
    "avgDurFmtPrev": "2분 50초",
    "avgCTR": 5.96,
    "avgCTRPrev": 6.48,
    "totalSubs": 2598,
    "totalSubsPrev": 19375,
    "subConv": 32.5,
    "subConvPrev": 86.9,
    "newViewers": 0,
    "newViewersPrev": 0,
    "reVisitors": 0,
    "reVisitorsPrev": 0,
    "newViewersPct": 0.0,
    "newViewersPctPrev": 0.0
  },
  "fixed": {
    "count": 328,
    "countPrev": 109,
    "avgViews": 61817,
    "watchTimeH": 1296964
  },
  "hotdug": {
    "cur": {
      "label": "HOTDUG",
      "count": 29,
      "avgViews": 77409,
      "watchTimeH": 218894,
      "subs": 749,
      "avgCTR": 7.71,
      "avgViewRate": 48.6
    },
    "prev": {
      "label": "#플레이볼",
      "count": 16,
      "avgViews": 133592,
      "watchTimeH": 253063,
      "subs": 2230,
      "avgCTR": 8.9,
      "avgViewRate": 46.3
    }
  },
  "top10": [
    {
      "title": "DAY6 성진이 부르는 오늘도 승리한다🔥#DAY6 #성진 #롯데자이언츠 #응원가",
      "views": 438524,
      "ctr": 6.4,
      "tag": "콜라보"
    },
    {
      "title": "[주간 예열🔥] 예열을 위한 미리 듣는 롯데자이언츠 응원가 시리즈 | 영광의 순간 feat. 데이식스 성진",
      "views": 375441,
      "ctr": 6.9,
      "tag": "콜라보"
    },
    {
      "title": "DAY6 성진이 부르는 영광의 순간🔥",
      "views": 308630,
      "ctr": 6.2,
      "tag": "콜라보"
    },
    {
      "title": "[주간 예열🔥] 예열을 위한 미리 듣는 롯데자이언츠 응원가 시리즈 | 승리를 위한 전진 feat. 데이식스 성진",
      "views": 219026,
      "ctr": 6.6,
      "tag": "콜라보"
    },
    {
      "title": "[주간 예열🔥] 예열을 위한 미리 듣는 롯데자이언츠 응원가 시리즈 | 오늘도 승리한다 feat. 데이식스 성진",
      "views": 212844,
      "ctr": 6.7,
      "tag": "콜라보"
    },
    {
      "title": "[AIM HIGH] 청백전 1차전 in 타이난🔥 #하이라이트",
      "views": 168828,
      "ctr": 6.5,
      "tag": "기획"
    },
    {
      "title": "롯데자이언츠X세븐일레븐 띠부씰 맞히기 게임🫵 | 대환장 인물퀴즈까지!",
      "views": 161819,
      "ctr": 5.2,
      "tag": "기획"
    },
    {
      "title": "[AIM HIGH] 루키 박정민의 첫 등판부터 청백전 첫 홈런포까지🔥 l 청백전 2차전 #스프링캠프",
      "views": 160943,
      "ctr": 6.9,
      "tag": "기획"
    },
    {
      "title": "\"2026시즌, 더 높은 비상을 위한 준비. 지금, AIM HIGH.\"",
      "views": 160529,
      "ctr": 7.8,
      "tag": "기획"
    },
    {
      "title": "하늘마저 붙잡고 싶었던 마지막 인사 | 정훈의 이야기",
      "views": 156048,
      "ctr": 8.4,
      "tag": "기획"
    }
  ],
  "burst": {
    "count": 21,
    "shortsCount": 16,
    "longformCount": 5,
    "avgCTR": 7.9,
    "avgViews": 67469,
    "shortsAvgViews": 40108,
    "totalViews": 979079,
    "channelAvgCTR": 7.09,
    "channelAvgViews": 91648,
    "byDate": [
      {
        "date": "2026-06-21",
        "count": 7,
        "shortsCount": 4,
        "longformCount": 3,
        "avgCTR": 8.03,
        "avgViews": 73747
      },
      {
        "date": "2026-06-22",
        "count": 14,
        "shortsCount": 12,
        "longformCount": 2,
        "avgCTR": 7.69,
        "avgViews": 58052
      }
    ],
    "videos": [
      {
        "title": "정우의 엄청난 팬서비스 | 롯데! 한 다이 됐나! #롯데자이언츠 #정우",
        "views": 142754,
        "ctr": 5.8,
        "category": "기획",
        "is_shorts": true
      },
      {
        "title": "오랜만에 만난 DAY6 성진과 김원중 | 머리카락 근황 토크(?) #롯데자이언츠 #DAY6 #성진",
        "views": 94338,
        "ctr": 7.1,
        "category": "기획",
        "is_shorts": true
      },
      {
        "title": "[HIGHLIGHT] 롯데 VS 키움(06.21) | 한동희의 선취 적시타와 김동현의 쓰리런, 팀의 리드를 지켜낸 불펜진!🔥",
        "views": 88351,
        "ctr": 7.2,
        "category": "고정",
        "is_shorts": false
      },
      {
        "title": "팬들과 함께 | 끝까지 포기하지 마 (Return to Giants' home)",
        "views": 82228,
        "ctr": 9.6,
        "category": "기획",
        "is_shorts": false
      },
      {
        "title": "점수 차를 벌리는 김동현의 쓰리런🔥 #핫클립 #김동현",
        "views": 75230,
        "ctr": 6.7,
        "category": "고정",
        "is_shorts": true
      },
      {
        "title": "[HOTDUG] 김동현의 쓰리런, 윤동희 멀티히트 활약🔥(06.21)",
        "views": 68517,
        "ctr": 8.7,
        "category": "고정",
        "is_shorts": false
      },
      {
        "title": "승리의 하이파이브✋",
        "views": 63384,
        "ctr": 9.4,
        "category": "고정",
        "is_shorts": true
      },
      {
        "title": "[HOTDUG] 투타 완벽 조화로 완성한 승리🔥 (06.20)",
        "views": 50662,
        "ctr": 7.3,
        "category": "고정",
        "is_shorts": false
      },
      {
        "title": "김원중이 가르쳐주는 슬라이더 | 시구자 최초(?) 변화구 시도? #롯데자이언츠 #DAY6 #성진",
        "views": 48187,
        "ctr": 6.9,
        "category": "기획",
        "is_shorts": true
      },
      {
        "title": "[전지적 동현 시점] 김동현이 들려주는 첫 안타, 첫 홈런 이야기✨",
        "views": 47586,
        "ctr": 6.7,
        "category": "기획",
        "is_shorts": false
      },
      {
        "title": "선취점을 얻어내는 한동희의 적시타🔥 #핫클립 #한동희",
        "views": 32016,
        "ctr": 3.0,
        "category": "고정",
        "is_shorts": true
      },
      {
        "title": "요리로 따지자면? | 윤남노다운 시구 소감✨ #롯데자이언츠 #윤남노",
        "views": 23603,
        "ctr": 2.4,
        "category": "기획",
        "is_shorts": true
      },
      {
        "title": "최준용의 시구 지도 소감 | 짱구야! 한 다이 됐나! #롯데자이언츠",
        "views": 22495,
        "ctr": 5.4,
        "category": "기획",
        "is_shorts": true
      },
      {
        "title": "공이랑 낯가리는 윤남노💦⚾️ (feat. 시구 지도 선생님 김진욱) #롯데자이언츠 #윤남노",
        "views": 22370,
        "ctr": 4.9,
        "category": "기획",
        "is_shorts": true
      },
      {
        "title": "시구 전 토크 | 윤남노가 등번호 11번을 한 이유? #롯데자이언츠 #윤남노",
        "views": 21833,
        "ctr": 4.8,
        "category": "기획",
        "is_shorts": true
      },
      {
        "title": "DAY6 성진과 함께하는 롯데자이언츠 아웃송 메들리🎵 #롯데자이언츠 #DAY6 #성진",
        "views": 21396,
        "ctr": 5.1,
        "category": "기획",
        "is_shorts": true
      },
      {
        "title": "궁금한 게 많은 정우의 시구 연습⚾️ with 시구 지도 선생님 최준용 #롯데자이언츠 #정우",
        "views": 19896,
        "ctr": 4.0,
        "category": "기획",
        "is_shorts": true
      },
      {
        "title": "파이팅 넘치는 정우의 시구 소감✨ #롯데자이언츠 #정우",
        "views": 18831,
        "ctr": 4.0,
        "category": "기획",
        "is_shorts": true
      },
      {
        "title": "LINEUP\n6월 21일 (일) vs 키움\n선발 라인업을 공개합니다🔥\n\n등록: -\n말소: -",
        "views": 12528,
        "ctr": 0.0,
        "category": "고정",
        "is_shorts": true
      },
      {
        "title": "DAY6 성진이 라이브로 부르는 영광의 순간✨ #롯데자이언츠 #DAY6 #성진",
        "views": 11782,
        "ctr": 4.6,
        "category": "기획",
        "is_shorts": true
      },
      {
        "title": "칭찬만 가득한 시구 연습 현장✨ with 시구 경력 만렙 성진 #롯데자이언츠 #DAY6 #성진",
        "views": 11092,
        "ctr": 3.5,
        "category": "기획",
        "is_shorts": true
      }
    ]
  },
  "timing": {
    "uploadVsImpr": [
      {
        "uploadCount": 1,
        "days": 28,
        "videoCount": 28,
        "avgImpr": 940104,
        "avgViews": 79347
      },
      {
        "uploadCount": 2,
        "days": 16,
        "videoCount": 32,
        "avgImpr": 989894,
        "avgViews": 86688
      },
      {
        "uploadCount": 3,
        "days": 11,
        "videoCount": 33,
        "avgImpr": 937691,
        "avgViews": 86288
      },
      {
        "uploadCount": 4,
        "days": 5,
        "videoCount": 20,
        "avgImpr": 816779,
        "avgViews": 73256
      },
      {
        "uploadCount": 5,
        "days": 1,
        "videoCount": 5,
        "avgImpr": 325206,
        "avgViews": 34176
      }
    ],
    "timelinessHL": [
      {
        "label": "D+0",
        "count": 29,
        "avgViews": 120790,
        "avgImpr": 1474960,
        "avgCTR": 6.81
      },
      {
        "label": "D+1",
        "count": 1,
        "avgViews": 57503,
        "avgImpr": 897031,
        "avgCTR": 5.22
      }
    ]
  },
  "contentTypeConv": {
    "typeStats": [
      {
        "type": "생중계",
        "count": 8,
        "conv": 73.9,
        "avgViews": 12294,
        "avgCTR": 3.6,
        "avgSubs": 6.8
      },
      {
        "type": "예능",
        "count": 2,
        "conv": 61.3,
        "avgViews": 150894,
        "avgCTR": 5.8,
        "avgSubs": 93.5
      },
      {
        "type": "전지훈련",
        "count": 10,
        "conv": 43.5,
        "avgViews": 132015,
        "avgCTR": 7.0,
        "avgSubs": 57.7
      },
      {
        "type": "기타기획",
        "count": 20,
        "conv": 35.5,
        "avgViews": 82055,
        "avgCTR": 6.9,
        "avgSubs": 31.7
      },
      {
        "type": "공식행사",
        "count": 5,
        "conv": 29.4,
        "avgViews": 97106,
        "avgCTR": 6.3,
        "avgSubs": 32.8
      },
      {
        "type": "화보",
        "count": 3,
        "conv": 27.6,
        "avgViews": 86113,
        "avgCTR": 6.2,
        "avgSubs": 24.7
      },
      {
        "type": "인터뷰/예고",
        "count": 2,
        "conv": 23.9,
        "avgViews": 78457,
        "avgCTR": 6.9,
        "avgSubs": 19.0
      }
    ],
    "catCompare": [
      {
        "label": "기획 롱폼",
        "count": 52,
        "conv": 42.3,
        "avgViews": 86145,
        "totalSubs": 1797
      },
      {
        "label": "기획 숏츠",
        "count": 42,
        "conv": 13.3,
        "avgViews": 83393,
        "totalSubs": 801
      },
      {
        "label": "고정 롱폼",
        "count": 109,
        "conv": 47.4,
        "avgViews": 93165,
        "totalSubs": 5164
      }
    ]
  },
  "direction": [
    {
      "label": "감성/브랜딩형",
      "count": 42,
      "shortsCount": 24,
      "longformCount": 18,
      "avgViews": 125083,
      "avgCTR": 7.4,
      "avgImpr": 749505,
      "conv": 30.3,
      "convLongform": 47.5,
      "avgNewViewerPct": 4.4,
      "avgShares": 110,
      "avgLikes": 336,
      "avgRPM": 1586,
      "videos": [
        {
          "title": "DAY6 성진이 부르는 오늘도 승리한다🔥#DAY6 #성진 #롯데자이언츠 #응원가",
          "date": "03/13",
          "views": 438524,
          "ctr": 6.39,
          "conv": 13.5,
          "isShorts": true,
          "newViewerPct": 9.7,
          "shares": 139,
          "likes": 525,
          "rpm": 318
        },
        {
          "title": "[주간 예열🔥] 예열을 위한 미리 듣는 롯데자이언츠 응원가 시리즈 | 영광의 순간 feat. 데이식스 성진",
          "date": "03/14",
          "views": 375441,
          "ctr": 6.88,
          "conv": 47.9,
          "isShorts": true,
          "newViewerPct": 18.6,
          "shares": 1185,
          "likes": 1249,
          "rpm": 1375
        },
        {
          "title": "[미야자키 연습경기 생중계] vs 세이부라이온즈(2/22)",
          "date": "02/22",
          "views": 371114,
          "ctr": 15.71,
          "conv": 109.1,
          "isShorts": false,
          "newViewerPct": 9.7,
          "shares": 6,
          "likes": -27,
          "rpm": 0
        },
        {
          "title": "DAY6 성진이 부르는 영광의 순간🔥",
          "date": "03/14",
          "views": 308630,
          "ctr": 6.21,
          "conv": 6.8,
          "isShorts": true,
          "newViewerPct": 3.5,
          "shares": 47,
          "likes": 431,
          "rpm": 308
        },
        {
          "title": "[미야자키 구춘리그] vs 지바롯데마린스 (3/1)",
          "date": "03/01",
          "views": 292968,
          "ctr": 14.08,
          "conv": 75.1,
          "isShorts": false,
          "newViewerPct": 8.5,
          "shares": 3,
          "likes": -15,
          "rpm": 0
        },
        {
          "title": "[미야자키 연습경기] vs SSG (3/3)",
          "date": "03/03",
          "views": 245924,
          "ctr": 14.92,
          "conv": 95.2,
          "isShorts": false,
          "newViewerPct": 5.7,
          "shares": 6,
          "likes": -8,
          "rpm": 10162
        },
        {
          "title": "[미야자키 연습경기 생중계] vs 요미우리자이언츠(2/23)",
          "date": "02/23",
          "views": 236768,
          "ctr": 15.89,
          "conv": 68.4,
          "isShorts": false,
          "newViewerPct": 10.5,
          "shares": 3,
          "likes": -7,
          "rpm": 4906
        },
        {
          "title": "[미야자키 구춘리그] vs 두산베어스(2/26)",
          "date": "02/26",
          "views": 228065,
          "ctr": 15.92,
          "conv": 53.1,
          "isShorts": false,
          "newViewerPct": 9.2,
          "shares": 0,
          "likes": -11,
          "rpm": 1341
        },
        {
          "title": "[주간 예열🔥] 예열을 위한 미리 듣는 롯데자이언츠 응원가 시리즈 | 승리를 위한 전진 feat. 데이식스 성진",
          "date": "03/13",
          "views": 219026,
          "ctr": 6.63,
          "conv": 46.1,
          "isShorts": true,
          "newViewerPct": 6.0,
          "shares": 523,
          "likes": 574,
          "rpm": 1336
        },
        {
          "title": "[미야자키 구춘리그] 빗속을 가르는 두 개의 홈런포🔥 #김민성 #레이예스",
          "date": "02/26",
          "views": 214875,
          "ctr": 8.5,
          "conv": 7.4,
          "isShorts": true,
          "newViewerPct": 1.4,
          "shares": 0,
          "likes": -7,
          "rpm": 348
        }
      ]
    },
    {
      "label": "예능/참여형",
      "count": 22,
      "shortsCount": 4,
      "longformCount": 18,
      "avgViews": 91915,
      "avgCTR": 6.5,
      "avgImpr": 975465,
      "conv": 27.4,
      "convLongform": 32.7,
      "avgNewViewerPct": 1.3,
      "avgShares": 253,
      "avgLikes": 1507,
      "avgRPM": 1545,
      "videos": [
        {
          "title": "하늘마저 붙잡고 싶었던 마지막 인사 | 정훈의 이야기",
          "date": "04/18",
          "views": 156048,
          "ctr": 8.43,
          "conv": 26.9,
          "isShorts": false,
          "newViewerPct": 2.6,
          "shares": 752,
          "likes": 4989,
          "rpm": 1770
        },
        {
          "title": "등장곡 바꿀 선수는 여기로 오세요!✨ 2026 시즌 등장곡 드래프트",
          "date": "03/24",
          "views": 152440,
          "ctr": 6.19,
          "conv": 42.6,
          "isShorts": false,
          "newViewerPct": 1.2,
          "shares": 75,
          "likes": 463,
          "rpm": 0
        },
        {
          "title": "비시즌에 뭐 했어요? #롯데자이언츠",
          "date": "01/28",
          "views": 144143,
          "ctr": 7.44,
          "conv": 38.2,
          "isShorts": false,
          "newViewerPct": 0.4,
          "shares": 7,
          "likes": 127,
          "rpm": 0
        },
        {
          "title": "사직야구장 신메뉴 먹방 3코스 | 직관가서 뭐 먹지?🤔",
          "date": "04/29",
          "views": 139969,
          "ctr": 6.44,
          "conv": 52.2,
          "isShorts": false,
          "newViewerPct": 2.1,
          "shares": 1530,
          "likes": 2898,
          "rpm": 2722
        },
        {
          "title": "화이트데이 특집 | 먹을 수만 있게 만들어라 흑백두쫀쿠👩‍🍳🧆",
          "date": "03/14",
          "views": 119734,
          "ctr": 5.38,
          "conv": 41.8,
          "isShorts": false,
          "newViewerPct": 4.7,
          "shares": 44,
          "likes": 260,
          "rpm": 2347
        },
        {
          "title": "한태양의 NEW 응원가 공개🎶(with 윤동희, 이호준)",
          "date": "03/25",
          "views": 112718,
          "ctr": 9.84,
          "conv": 31.1,
          "isShorts": false,
          "newViewerPct": 2.9,
          "shares": 128,
          "likes": 352,
          "rpm": 1763
        },
        {
          "title": "건강한 복귀와 첫 승리!✨ 1승이 간절했던 순간들 l 주간 이슈",
          "date": "04/15",
          "views": 108989,
          "ctr": 7.07,
          "conv": 27.5,
          "isShorts": false,
          "newViewerPct": 1.0,
          "shares": 170,
          "likes": 3118,
          "rpm": 2322
        },
        {
          "title": "전지훈련 비행 브이로그 ✈️ | with 이스타항공, 그런데 이제.. 롯데고사를 곁들인",
          "date": "02/04",
          "views": 104642,
          "ctr": 7.63,
          "conv": 32.5,
          "isShorts": false,
          "newViewerPct": 0.5,
          "shares": 10,
          "likes": 123,
          "rpm": 0
        },
        {
          "title": "팬 여러분, 엘빈 선수 등장곡을 추천해 주세요!🎵",
          "date": "03/24",
          "views": 104485,
          "ctr": 6.18,
          "conv": 4.8,
          "isShorts": true,
          "newViewerPct": 0.5,
          "shares": 3,
          "likes": 322,
          "rpm": 319
        },
        {
          "title": "“와… 멋있는데?✨” 비주얼 대폭발한 프로필 촬영 현장! [1편] #프로필촬영 #비하인드",
          "date": "01/31",
          "views": 104295,
          "ctr": 5.88,
          "conv": 35.5,
          "isShorts": false,
          "newViewerPct": 0.2,
          "shares": 9,
          "likes": 75,
          "rpm": 2569
        }
      ]
    }
  ],
  "criteria": {
    "averages": {
      "count": 161,
      "avgCTR": 7.11,
      "avgRetention": 38.6,
      "avgShareRate": 2.25,
      "avgLikeRate": 19.73,
      "avgSubConv": 45.7,
      "avgWatchH": 9853.2
    },
    "rankings": {
      "ctr": [
        {
          "title": "[HOTDUG] 박세웅의 호투에 응답하는 득점🙌🏻(05.10)",
          "date": "2026.05.11",
          "category": "고정",
          "views": 172351,
          "ctr": 16.3,
          "retention": 20.6,
          "shareRate": 3.13,
          "likeRate": 10.96,
          "subConv": -90.5,
          "watchH": 7594.6
        },
        {
          "title": "[미야자키 구춘리그] vs 두산베어스(2/26)",
          "date": "2026.02.26",
          "category": "고정",
          "views": 228065,
          "ctr": 15.92,
          "retention": 9.8,
          "shareRate": 0,
          "likeRate": 0,
          "subConv": 53.1,
          "watchH": 28052.1
        },
        {
          "title": "[미야자키 연습경기 생중계] vs 요미우리자이언츠(2/23)",
          "date": "2026.02.23",
          "category": "고정",
          "views": 236768,
          "ctr": 15.89,
          "retention": 6.6,
          "shareRate": 0.01,
          "likeRate": 0,
          "subConv": 68.4,
          "watchH": 48930.2
        },
        {
          "title": "[미야자키 연습경기 생중계] vs 세이부라이온즈(2/22)",
          "date": "2026.02.22",
          "category": "고정",
          "views": 371114,
          "ctr": 15.71,
          "retention": 6.9,
          "shareRate": 0.02,
          "likeRate": 0,
          "subConv": 109.1,
          "watchH": 78262.7
        },
        {
          "title": "[미야자키 연습경기] vs SSG (3/3)",
          "date": "2026.03.03",
          "category": "고정",
          "views": 245924,
          "ctr": 14.92,
          "retention": 6.9,
          "shareRate": 0.02,
          "likeRate": 0,
          "subConv": 95.2,
          "watchH": 52362.6
        },
        {
          "title": "[미야자키 구춘리그] vs 지바롯데마린스 (3/1)",
          "date": "2026.03.01",
          "category": "고정",
          "views": 292968,
          "ctr": 14.08,
          "retention": 8.7,
          "shareRate": 0.01,
          "likeRate": 0,
          "subConv": 75.1,
          "watchH": 91274.5
        },
        {
          "title": "플레이로 보여준 책임감 | 승리로 답한 진심",
          "date": "2026.05.07",
          "category": "기획",
          "views": 81484,
          "ctr": 11.29,
          "retention": 34.6,
          "shareRate": 5.15,
          "likeRate": 20.86,
          "subConv": -23.3,
          "watchH": 2092.3
        },
        {
          "title": "한태양의 NEW 응원가 공개🎶(with 윤동희, 이호준)",
          "date": "2026.03.25",
          "category": "기획",
          "views": 112718,
          "ctr": 9.84,
          "retention": 49.3,
          "shareRate": 1.14,
          "likeRate": 3.12,
          "subConv": 31.1,
          "watchH": 3368.0
        },
        {
          "title": "팬들과 함께 | 끝까지 포기하지 마 (Return to Giants' home)",
          "date": "2026.06.21",
          "category": "기획",
          "views": 82228,
          "ctr": 9.59,
          "retention": 49.7,
          "shareRate": 17.06,
          "likeRate": 52.5,
          "subConv": 124.0,
          "watchH": 2590.4
        },
        {
          "title": "[AIM HIGH] 2026 롯데자이언츠 타이난 캠프 | 변함과 변화의 차이",
          "date": "2026.02.12",
          "category": "기획",
          "views": 154922,
          "ctr": 9.42,
          "retention": 29.0,
          "shareRate": 0.01,
          "likeRate": 0,
          "subConv": 18.1,
          "watchH": 5495.4
        },
        {
          "title": "마운드를 지배하는 압도적 투구 | No.31 로드리게스",
          "date": "2026.04.10",
          "category": "고정",
          "views": 84633,
          "ctr": 8.81,
          "retention": 52.4,
          "shareRate": 4.28,
          "likeRate": 43.66,
          "subConv": 50.8,
          "watchH": 4052.7
        },
        {
          "title": "[퓨처스리그] 롯데자이언츠 vs KT위즈(03.25)_1",
          "date": "2026.04.01",
          "category": "고정",
          "views": 35410,
          "ctr": 8.79,
          "retention": 3.6,
          "shareRate": 0.03,
          "likeRate": 0.14,
          "subConv": 39.5,
          "watchH": 2954.7
        },
        {
          "title": "[HOTDUG] 전민재의 데뷔 첫 만루홈런 & 나승엽의 연타석 홈런🔥(06.16)",
          "date": "2026.06.17",
          "category": "고정",
          "views": 57960,
          "ctr": 8.71,
          "retention": 45.1,
          "shareRate": 1.54,
          "likeRate": 31.52,
          "subConv": 22.4,
          "watchH": 4385.0
        },
        {
          "title": "[미야자키 구춘리그] 우천 취소 중계진 라이브 토크(2/26)",
          "date": "2026.02.26",
          "category": "고정",
          "views": 41919,
          "ctr": 8.7,
          "retention": 8.0,
          "shareRate": 0.02,
          "likeRate": 0,
          "subConv": 19.1,
          "watchH": 1174.3
        },
        {
          "title": "[HOTDUG] 불붙은 타선만큼 뜨거웠던 더그아웃🔥 (05.06)",
          "date": "2026.05.07",
          "category": "고정",
          "views": 89941,
          "ctr": 8.66,
          "retention": 55.9,
          "shareRate": 1.07,
          "likeRate": 27.87,
          "subConv": 27.8,
          "watchH": 7154.7
        },
        {
          "title": "[HOTDUG] 김동현의 쓰리런, 윤동희 멀티히트 활약🔥(06.21)",
          "date": "2026.06.22",
          "category": "고정",
          "views": 68517,
          "ctr": 8.65,
          "retention": 52.0,
          "shareRate": 1.53,
          "likeRate": 28.26,
          "subConv": 37.9,
          "watchH": 7174.2
        },
        {
          "title": "[HOTDUG] 시즌 첫 스윕 달성! 팽팽한 혈투 끝에 거둔 4연승! (05.03)",
          "date": "2026.05.04",
          "category": "고정",
          "views": 94001,
          "ctr": 8.52,
          "retention": 58.5,
          "shareRate": 1.26,
          "likeRate": 28.77,
          "subConv": 25.5,
          "watchH": 7567.7
        },
        {
          "title": "하늘마저 붙잡고 싶었던 마지막 인사 | 정훈의 이야기",
          "date": "2026.04.18",
          "category": "기획",
          "views": 156048,
          "ctr": 8.43,
          "retention": 33.6,
          "shareRate": 4.82,
          "likeRate": 31.97,
          "subConv": 26.9,
          "watchH": 7433.7
        },
        {
          "title": "[HIGHLIGHT] NC VS 롯데(06.23) | 노진혁의 솔로 홈런 & 윤동희의 끝내기 안타🔥",
          "date": "2026.06.23",
          "category": "고정",
          "views": 88534,
          "ctr": 8.4,
          "retention": 52.4,
          "shareRate": 0.94,
          "likeRate": 23.43,
          "subConv": 37.3,
          "watchH": 11366.8
        },
        {
          "title": "[퓨처스리그] 롯데자이언츠 vs KT위즈(03.26)",
          "date": "2026.04.01",
          "category": "고정",
          "views": 50380,
          "ctr": 8.4,
          "retention": 4.1,
          "shareRate": 0.18,
          "likeRate": 0.54,
          "subConv": 99.2,
          "watchH": 5888.7
        }
      ],
      "retention": [
        {
          "title": "전민재의 빈틈없는 플레이! | 전민재의 호수비 하이라이트",
          "date": "2026.05.04",
          "category": "기획",
          "views": 84247,
          "ctr": 6.15,
          "retention": 65.7,
          "shareRate": 12.25,
          "likeRate": 60.25,
          "subConv": 46.3,
          "watchH": 3027.7
        },
        {
          "title": "[HIGHLIGHT] 롯데 VS SSG (05.03) | 레이예스의 역전 쓰리런! SSG전 스윕승!🔥",
          "date": "2026.05.03",
          "category": "고정",
          "views": 153218,
          "ctr": 7.03,
          "retention": 60.6,
          "shareRate": 1.03,
          "likeRate": 18.06,
          "subConv": 39.8,
          "watchH": 15133.0
        },
        {
          "title": "[HIGHLIGHT] 롯데 VS 키움(06.21) | 한동희의 선취 적시타와 김동현의 쓰리런, 팀의 리드를 지켜낸 불펜진!🔥",
          "date": "2026.06.21",
          "category": "고정",
          "views": 88351,
          "ctr": 7.2,
          "retention": 59.1,
          "shareRate": 0.78,
          "likeRate": 18.12,
          "subConv": 37.4,
          "watchH": 8987.3
        },
        {
          "title": "[HIGHLIGHT] 롯데 VS SSG (05.02) | 나균안 7이닝 호투 & 6회 타선 폭발! SSG전 위닝 시리즈 확정⚾",
          "date": "2026.05.02",
          "category": "고정",
          "views": 181646,
          "ctr": 8.15,
          "retention": 58.7,
          "shareRate": 0.79,
          "likeRate": 15.77,
          "subConv": 44.0,
          "watchH": 27649.2
        },
        {
          "title": "광고보다 더 귀엽다… 레이예스 촬영장 NG 모음.zip | YES or NO 인터뷰까지!",
          "date": "2026.05.01",
          "category": "기획",
          "views": 99821,
          "ctr": 7.68,
          "retention": 58.6,
          "shareRate": 5.64,
          "likeRate": 34.69,
          "subConv": 25.0,
          "watchH": 3120.3
        },
        {
          "title": "[HOTDUG] 시즌 첫 스윕 달성! 팽팽한 혈투 끝에 거둔 4연승! (05.03)",
          "date": "2026.05.04",
          "category": "고정",
          "views": 94001,
          "ctr": 8.52,
          "retention": 58.5,
          "shareRate": 1.26,
          "likeRate": 28.77,
          "subConv": 25.5,
          "watchH": 7567.7
        },
        {
          "title": "[HIGHLIGHT] 롯데 VS KIA(06.03) | 김진욱의 호투와 황성빈의 만점 활약🔥",
          "date": "2026.06.03",
          "category": "고정",
          "views": 111663,
          "ctr": 5.97,
          "retention": 57.8,
          "shareRate": 0.67,
          "likeRate": 17.16,
          "subConv": 29.6,
          "watchH": 17254.6
        },
        {
          "title": "[HIGHLIGHT] 롯데 VS 두산 (04.23) | 로드리게스의 111구, 전민재 공수 대활약🔥",
          "date": "2026.04.23",
          "category": "고정",
          "views": 121331,
          "ctr": 6.94,
          "retention": 57.8,
          "shareRate": 0.93,
          "likeRate": 17.77,
          "subConv": 28.8,
          "watchH": 15449.8
        },
        {
          "title": "등장곡 바꿀 선수는 여기로 오세요!✨ 2026 시즌 등장곡 드래프트",
          "date": "2026.03.24",
          "category": "기획",
          "views": 152440,
          "ctr": 6.19,
          "retention": 57.4,
          "shareRate": 0.49,
          "likeRate": 3.04,
          "subConv": 42.6,
          "watchH": 11955.5
        },
        {
          "title": "[HIGHLIGHT] 롯데 VS 한화(05.19) | 전민재·한동희 홈런포 & 거침없는 주루 플레이!🔥",
          "date": "2026.05.19",
          "category": "고정",
          "views": 153716,
          "ctr": 6.92,
          "retention": 57.1,
          "shareRate": 0.9,
          "likeRate": 17.9,
          "subConv": 46.8,
          "watchH": 23838.9
        },
        {
          "title": "[HIGHLIGHT] 롯데 VS KT (05.06) | 제대로 불붙은 타선의 화력!",
          "date": "2026.05.06",
          "category": "고정",
          "views": 175346,
          "ctr": 8.19,
          "retention": 57.1,
          "shareRate": 1.0,
          "likeRate": 18.6,
          "subConv": 33.1,
          "watchH": 25768.0
        },
        {
          "title": "[HIGHLIGHT] 롯데 VS 키움(06.20) | 선발 나균안의 호투와 레이예스 3타점 맹활약, 한동희·윤동희의 적시타 속 승리!🔥",
          "date": "2026.06.20",
          "category": "고정",
          "views": 91351,
          "ctr": 6.37,
          "retention": 56.8,
          "shareRate": 0.71,
          "likeRate": 15.62,
          "subConv": 25.2,
          "watchH": 12964.4
        },
        {
          "title": "[HIGHLIGHT] 롯데 VS 키움 (04.30) | 비슬리의 호투 & 타선의 집중력으로 만든 위닝시리즈🔥",
          "date": "2026.04.30",
          "category": "고정",
          "views": 72699,
          "ctr": 7.26,
          "retention": 56.1,
          "shareRate": 0.61,
          "likeRate": 17.54,
          "subConv": 17.9,
          "watchH": 10408.0
        },
        {
          "title": "[HOTDUG] 8이닝 무사사구! 2경기 연속 도미넌트 스타트🔥(04.10)",
          "date": "2026.04.11",
          "category": "고정",
          "views": 108337,
          "ctr": 7.81,
          "retention": 56.0,
          "shareRate": 1.54,
          "likeRate": 29.51,
          "subConv": 60.9,
          "watchH": 8831.6
        },
        {
          "title": "[HOTDUG] 불붙은 타선만큼 뜨거웠던 더그아웃🔥 (05.06)",
          "date": "2026.05.07",
          "category": "고정",
          "views": 89941,
          "ctr": 8.66,
          "retention": 55.9,
          "shareRate": 1.07,
          "likeRate": 27.87,
          "subConv": 27.8,
          "watchH": 7154.7
        },
        {
          "title": "[HIGHLIGHT] 롯데 VS 키움 (06.19) | 이민석의 첫 QS+🔥 그리고 끝까지 지켜낸 1점 차 승리!",
          "date": "2026.06.19",
          "category": "고정",
          "views": 86990,
          "ctr": 6.86,
          "retention": 55.9,
          "shareRate": 0.6,
          "likeRate": 18.45,
          "subConv": 21.8,
          "watchH": 11001.5
        },
        {
          "title": "전지훈련 가는데 이건 왜 챙겨?🤣 전지훈련 가방 탈탈 털어봤습니다! | What's in your bag?",
          "date": "2026.02.02",
          "category": "기획",
          "views": 101012,
          "ctr": 6.38,
          "retention": 55.8,
          "shareRate": 0.19,
          "likeRate": 1.79,
          "subConv": 27.7,
          "watchH": 6281.6
        },
        {
          "title": "[HIGHLIGHT] 롯데 VS LG (06.12) | 황성빈 5타점 맹활약과 손호영의 쓰리런, 로드리게스의 호투 속 완승!🔥",
          "date": "2026.06.12",
          "category": "고정",
          "views": 131740,
          "ctr": 6.16,
          "retention": 55.8,
          "shareRate": 1.09,
          "likeRate": 17.69,
          "subConv": 33.4,
          "watchH": 18483.7
        },
        {
          "title": "[HIGHLIGHT] 롯데 VS LG (04.15) 빈틈없는 무실점 릴레이와 응집력으로 일궈낸 승리!",
          "date": "2026.04.15",
          "category": "고정",
          "views": 163253,
          "ctr": 7.56,
          "retention": 55.8,
          "shareRate": 1.27,
          "likeRate": 20.81,
          "subConv": 57.0,
          "watchH": 18869.1
        },
        {
          "title": "[HIGHLIGHT] 삼성 VS 롯데(05.23) | 응집력 있는 타선으로 완성한 역전승!",
          "date": "2026.05.23",
          "category": "고정",
          "views": 112803,
          "ctr": 7.15,
          "retention": 55.1,
          "shareRate": 0.98,
          "likeRate": 15.35,
          "subConv": 34.6,
          "watchH": 14252.7
        }
      ],
      "likeRate": [
        {
          "title": "전민재의 빈틈없는 플레이! | 전민재의 호수비 하이라이트",
          "date": "2026.05.04",
          "category": "기획",
          "views": 84247,
          "ctr": 6.15,
          "retention": 65.7,
          "shareRate": 12.25,
          "likeRate": 60.25,
          "subConv": 46.3,
          "watchH": 3027.7
        },
        {
          "title": "단장님을 울린 팬들의 떼창 | 조지훈의 20주년",
          "date": "2026.04.23",
          "category": "기획",
          "views": 103485,
          "ctr": 7.01,
          "retention": 48.6,
          "shareRate": 10.21,
          "likeRate": 54.0,
          "subConv": 35.8,
          "watchH": 4495.9
        },
        {
          "title": "9년의 기다림 | 현도훈의 데뷔 첫 승 G캠 (4K)",
          "date": "2026.04.28",
          "category": "고정",
          "views": 39043,
          "ctr": 7.55,
          "retention": 52.6,
          "shareRate": 5.33,
          "likeRate": 53.22,
          "subConv": 33.3,
          "watchH": 1762.4
        },
        {
          "title": "팬들과 함께 | 끝까지 포기하지 마 (Return to Giants' home)",
          "date": "2026.06.21",
          "category": "기획",
          "views": 82228,
          "ctr": 9.59,
          "retention": 49.7,
          "shareRate": 17.06,
          "likeRate": 52.5,
          "subConv": 124.0,
          "watchH": 2590.4
        },
        {
          "title": "[퓨처스리그] 롯데자이언츠 vs KT위즈(03.25)",
          "date": "2026.04.01",
          "category": "고정",
          "views": 301,
          "ctr": 1.78,
          "retention": 0.3,
          "shareRate": 3.32,
          "likeRate": 46.51,
          "subConv": 0.0,
          "watchH": 1.2
        },
        {
          "title": "차분한 남자 현도훈, 특별한 루틴을 공개합니다👀 | 현도훈 50문 50답",
          "date": "2026.06.23",
          "category": "기획",
          "views": 37353,
          "ctr": 6.54,
          "retention": 49.3,
          "shareRate": 4.93,
          "likeRate": 46.29,
          "subConv": 24.1,
          "watchH": 3429.3
        },
        {
          "title": "롯데자이언츠 신인 최초 개막전 세이브 | No.36 박정민",
          "date": "2026.03.28",
          "category": "고정",
          "views": 126549,
          "ctr": 7.73,
          "retention": 49.0,
          "shareRate": 5.03,
          "likeRate": 44.51,
          "subConv": 72.7,
          "watchH": 5135.9
        },
        {
          "title": "끈질긴 집중력과 역전의 순간 | 빅이닝 G캠",
          "date": "2026.05.01",
          "category": "고정",
          "views": 47926,
          "ctr": 7.28,
          "retention": 52.4,
          "shareRate": 1.71,
          "likeRate": 43.8,
          "subConv": 20.9,
          "watchH": 2404.9
        },
        {
          "title": "마운드를 지배하는 압도적 투구 | No.31 로드리게스",
          "date": "2026.04.10",
          "category": "고정",
          "views": 84633,
          "ctr": 8.81,
          "retention": 52.4,
          "shareRate": 4.28,
          "likeRate": 43.66,
          "subConv": 50.8,
          "watchH": 4052.7
        },
        {
          "title": "ep.5 누리라이브 벚꽃누리랑 누리랑🌸",
          "date": "2026.04.29",
          "category": "기획",
          "views": 3928,
          "ctr": 2.41,
          "retention": 17.6,
          "shareRate": 7.64,
          "likeRate": 41.5,
          "subConv": 76.4,
          "watchH": 42.1
        },
        {
          "title": "ep4. 누리라이브 조지훈 단장님 깜짝 이벤트! (자막 있음) #20주년",
          "date": "2026.04.22",
          "category": "기획",
          "views": 35499,
          "ctr": 6.54,
          "retention": 35.9,
          "shareRate": 9.86,
          "likeRate": 41.35,
          "subConv": 33.8,
          "watchH": 909.1
        },
        {
          "title": "어버이날 시구 비하인드 | 김진욱과 손성빈의 깜짝 효도 프로젝트✨",
          "date": "2026.06.18",
          "category": "기획",
          "views": 61200,
          "ctr": 6.12,
          "retention": 44.1,
          "shareRate": 4.85,
          "likeRate": 39.26,
          "subConv": 40.8,
          "watchH": 7136.0
        },
        {
          "title": "[전지적 동현 시점] 김동현이 들려주는 첫 안타, 첫 홈런 이야기✨",
          "date": "2026.06.22",
          "category": "기획",
          "views": 47586,
          "ctr": 6.73,
          "retention": 36.6,
          "shareRate": 2.88,
          "likeRate": 38.94,
          "subConv": 27.3,
          "watchH": 5096.4
        },
        {
          "title": "GIANTS OOTDㅣ선수단의 특별했던 포토카드 촬영 현장 비하인드✨📸",
          "date": "2026.06.23",
          "category": "기획",
          "views": 63822,
          "ctr": 7.3,
          "retention": 49.5,
          "shareRate": 9.65,
          "likeRate": 36.93,
          "subConv": 36.0,
          "watchH": 5832.9
        },
        {
          "title": "[HOTDUG] 박세웅의 퀄리티 스타트 투구와 이틀 연속 터지는 전민재의 역전 홈런🔥(06.17)",
          "date": "2026.06.18",
          "category": "고정",
          "views": 44944,
          "ctr": 7.04,
          "retention": 51.9,
          "shareRate": 1.6,
          "likeRate": 36.33,
          "subConv": 35.6,
          "watchH": 4273.8
        },
        {
          "title": "7이닝 2실점의 역투 | 나균안의 시즌 첫 승 G캠",
          "date": "2026.05.02",
          "category": "고정",
          "views": 62160,
          "ctr": 7.18,
          "retention": 45.9,
          "shareRate": 1.74,
          "likeRate": 35.63,
          "subConv": 16.1,
          "watchH": 3068.7
        },
        {
          "title": "[HOTDUG] 이민석의 QS+ 투구 & 전민재의 공수 맹활약🔥 (06.19)",
          "date": "2026.06.20",
          "category": "고정",
          "views": 47026,
          "ctr": 7.51,
          "retention": 54.2,
          "shareRate": 1.45,
          "likeRate": 35.07,
          "subConv": 23.4,
          "watchH": 4203.9
        },
        {
          "title": "[HOTDUG] 엘빈의 111구 투구와 공수 맹활약의 전민재🔥(04.23)",
          "date": "2026.04.24",
          "category": "고정",
          "views": 53017,
          "ctr": 7.52,
          "retention": 53.6,
          "shareRate": 2.02,
          "likeRate": 35.03,
          "subConv": 11.3,
          "watchH": 4828.5
        },
        {
          "title": "역전의 순간 | 균형을 깨는 황성빈의 결승 3루타 G캠",
          "date": "2026.05.29",
          "category": "고정",
          "views": 31472,
          "ctr": 6.85,
          "retention": 43.2,
          "shareRate": 2.51,
          "likeRate": 34.76,
          "subConv": 28.6,
          "watchH": 1030.1
        },
        {
          "title": "광고보다 더 귀엽다… 레이예스 촬영장 NG 모음.zip | YES or NO 인터뷰까지!",
          "date": "2026.05.01",
          "category": "기획",
          "views": 99821,
          "ctr": 7.68,
          "retention": 58.6,
          "shareRate": 5.64,
          "likeRate": 34.69,
          "subConv": 25.0,
          "watchH": 3120.3
        }
      ],
      "shareRate": [
        {
          "title": "[Playlist] 야수 등장곡+응원가 안무 버전✨ #직관전필수시청",
          "date": "2026.04.09",
          "category": "고정",
          "views": 255242,
          "ctr": 7.41,
          "retention": 24.8,
          "shareRate": 17.72,
          "likeRate": 13.5,
          "subConv": 98.7,
          "watchH": 23775.6
        },
        {
          "title": "팬들과 함께 | 끝까지 포기하지 마 (Return to Giants' home)",
          "date": "2026.06.21",
          "category": "기획",
          "views": 82228,
          "ctr": 9.59,
          "retention": 49.7,
          "shareRate": 17.06,
          "likeRate": 52.5,
          "subConv": 124.0,
          "watchH": 2590.4
        },
        {
          "title": "[Playlist] 2026 롯데자이언츠 팀 응원가 + 신규 응원가 포함! #직관전필수시청",
          "date": "2026.03.28",
          "category": "고정",
          "views": 330669,
          "ctr": 8.14,
          "retention": 19.5,
          "shareRate": 13.65,
          "likeRate": 15.86,
          "subConv": 74.1,
          "watchH": 47870.2
        },
        {
          "title": "ep.6 누리라이브 포켓몬데이⚡️💛",
          "date": "2026.05.08",
          "category": "기획",
          "views": 10125,
          "ctr": 3.42,
          "retention": 11.1,
          "shareRate": 13.63,
          "likeRate": 29.83,
          "subConv": 59.3,
          "watchH": 221.2
        },
        {
          "title": "전민재의 빈틈없는 플레이! | 전민재의 호수비 하이라이트",
          "date": "2026.05.04",
          "category": "기획",
          "views": 84247,
          "ctr": 6.15,
          "retention": 65.7,
          "shareRate": 12.25,
          "likeRate": 60.25,
          "subConv": 46.3,
          "watchH": 3027.7
        },
        {
          "title": "사직야구장 신메뉴 먹방 3코스 | 직관가서 뭐 먹지?🤔",
          "date": "2026.04.29",
          "category": "기획",
          "views": 139969,
          "ctr": 6.44,
          "retention": 38.2,
          "shareRate": 10.93,
          "likeRate": 20.7,
          "subConv": 52.2,
          "watchH": 14559.2
        },
        {
          "title": "ep.2 누리라이브 포켓몬데이 광장행사 🎉",
          "date": "2026.04.04",
          "category": "기획",
          "views": 14221,
          "ctr": 3.53,
          "retention": 8.7,
          "shareRate": 10.55,
          "likeRate": 20.88,
          "subConv": 35.2,
          "watchH": 218.1
        },
        {
          "title": "단장님을 울린 팬들의 떼창 | 조지훈의 20주년",
          "date": "2026.04.23",
          "category": "기획",
          "views": 103485,
          "ctr": 7.01,
          "retention": 48.6,
          "shareRate": 10.21,
          "likeRate": 54.0,
          "subConv": 35.8,
          "watchH": 4495.9
        },
        {
          "title": "ep4. 누리라이브 조지훈 단장님 깜짝 이벤트! (자막 있음) #20주년",
          "date": "2026.04.22",
          "category": "기획",
          "views": 35499,
          "ctr": 6.54,
          "retention": 35.9,
          "shareRate": 9.86,
          "likeRate": 41.35,
          "subConv": 33.8,
          "watchH": 909.1
        },
        {
          "title": "GIANTS OOTDㅣ선수단의 특별했던 포토카드 촬영 현장 비하인드✨📸",
          "date": "2026.06.23",
          "category": "기획",
          "views": 63822,
          "ctr": 7.3,
          "retention": 49.5,
          "shareRate": 9.65,
          "likeRate": 36.93,
          "subConv": 36.0,
          "watchH": 5832.9
        },
        {
          "title": "ep.1 누리라이브 개막식 현장 라이브",
          "date": "2026.04.03",
          "category": "기획",
          "views": 14782,
          "ctr": 4.23,
          "retention": 17.1,
          "shareRate": 7.85,
          "likeRate": 24.49,
          "subConv": -20.3,
          "watchH": 297.6
        },
        {
          "title": "ep.5 누리라이브 벚꽃누리랑 누리랑🌸",
          "date": "2026.04.29",
          "category": "기획",
          "views": 3928,
          "ctr": 2.41,
          "retention": 17.6,
          "shareRate": 7.64,
          "likeRate": 41.5,
          "subConv": 76.4,
          "watchH": 42.1
        },
        {
          "title": "가정의 달 특집 | 부산현대미술관 《코뿔소와 유니콘》 촬영 비하인드 📚🎥",
          "date": "2026.05.07",
          "category": "기획",
          "views": 58936,
          "ctr": 6.34,
          "retention": 38.3,
          "shareRate": 6.24,
          "likeRate": 29.61,
          "subConv": 22.1,
          "watchH": 3426.8
        },
        {
          "title": "광고보다 더 귀엽다… 레이예스 촬영장 NG 모음.zip | YES or NO 인터뷰까지!",
          "date": "2026.05.01",
          "category": "기획",
          "views": 99821,
          "ctr": 7.68,
          "retention": 58.6,
          "shareRate": 5.64,
          "likeRate": 34.69,
          "subConv": 25.0,
          "watchH": 3120.3
        },
        {
          "title": "롯데자이언츠X세븐일레븐 띠부씰 맞히기 게임🫵 | 대환장 인물퀴즈까지!",
          "date": "2026.05.03",
          "category": "기획",
          "views": 161819,
          "ctr": 5.16,
          "retention": 54.0,
          "shareRate": 5.53,
          "likeRate": 24.56,
          "subConv": 70.4,
          "watchH": 17883.3
        },
        {
          "title": "9년의 기다림 | 현도훈의 데뷔 첫 승 G캠 (4K)",
          "date": "2026.04.28",
          "category": "고정",
          "views": 39043,
          "ctr": 7.55,
          "retention": 52.6,
          "shareRate": 5.33,
          "likeRate": 53.22,
          "subConv": 33.3,
          "watchH": 1762.4
        },
        {
          "title": "플레이로 보여준 책임감 | 승리로 답한 진심",
          "date": "2026.05.07",
          "category": "기획",
          "views": 81484,
          "ctr": 11.29,
          "retention": 34.6,
          "shareRate": 5.15,
          "likeRate": 20.86,
          "subConv": -23.3,
          "watchH": 2092.3
        },
        {
          "title": "롯데자이언츠 신인 최초 개막전 세이브 | No.36 박정민",
          "date": "2026.03.28",
          "category": "고정",
          "views": 126549,
          "ctr": 7.73,
          "retention": 49.0,
          "shareRate": 5.03,
          "likeRate": 44.51,
          "subConv": 72.7,
          "watchH": 5135.9
        },
        {
          "title": "차분한 남자 현도훈, 특별한 루틴을 공개합니다👀 | 현도훈 50문 50답",
          "date": "2026.06.23",
          "category": "기획",
          "views": 37353,
          "ctr": 6.54,
          "retention": 49.3,
          "shareRate": 4.93,
          "likeRate": 46.29,
          "subConv": 24.1,
          "watchH": 3429.3
        },
        {
          "title": "어버이날 시구 비하인드 | 김진욱과 손성빈의 깜짝 효도 프로젝트✨",
          "date": "2026.06.18",
          "category": "기획",
          "views": 61200,
          "ctr": 6.12,
          "retention": 44.1,
          "shareRate": 4.85,
          "likeRate": 39.26,
          "subConv": 40.8,
          "watchH": 7136.0
        }
      ],
      "subConv": [
        {
          "title": "누리라이브 ep7. 3,4월 mvp시상식🏆",
          "date": "2026.05.10",
          "category": "기획",
          "views": 10481,
          "ctr": 3.13,
          "retention": 12.8,
          "shareRate": 2.29,
          "likeRate": 30.15,
          "subConv": 200.4,
          "watchH": 263.3
        },
        {
          "title": "[퓨처스리그] 롯데자이언츠 vs 기아 타이거즈 (05.13)",
          "date": "2026.05.14",
          "category": "고정",
          "views": 43309,
          "ctr": 6.43,
          "retention": 37.9,
          "shareRate": 1.5,
          "likeRate": 6.47,
          "subConv": 145.5,
          "watchH": 3919.7
        },
        {
          "title": "[퓨처스리그] 롯데자이언츠 vs 삼성라이온즈 (06.07)",
          "date": "2026.06.07",
          "category": "고정",
          "views": 36807,
          "ctr": 6.72,
          "retention": 3.2,
          "shareRate": 1.74,
          "likeRate": 8.53,
          "subConv": 138.6,
          "watchH": 3249.1
        },
        {
          "title": "[퓨처스리그] 롯데자이언츠 vs 한화 이글스 (05.06)",
          "date": "2026.05.06",
          "category": "고정",
          "views": 59032,
          "ctr": 8.16,
          "retention": 36.5,
          "shareRate": 2.22,
          "likeRate": 6.78,
          "subConv": 130.4,
          "watchH": 6620.5
        },
        {
          "title": "누리라이브 ep.8 마스코트와 함께하는 클래식씨리즈!",
          "date": "2026.05.24",
          "category": "기획",
          "views": 5428,
          "ctr": 2.26,
          "retention": 18.5,
          "shareRate": 1.11,
          "likeRate": 15.29,
          "subConv": 129.0,
          "watchH": 90.3
        },
        {
          "title": "[퓨처스리그] 롯데자이언츠 vs 울산웨일즈 (06.01)",
          "date": "2026.06.01",
          "category": "고정",
          "views": 32365,
          "ctr": 6.97,
          "retention": 3.2,
          "shareRate": 1.64,
          "likeRate": 9.02,
          "subConv": 126.7,
          "watchH": 3064.2
        },
        {
          "title": "팬들과 함께 | 끝까지 포기하지 마 (Return to Giants' home)",
          "date": "2026.06.21",
          "category": "기획",
          "views": 82228,
          "ctr": 9.59,
          "retention": 49.7,
          "shareRate": 17.06,
          "likeRate": 52.5,
          "subConv": 124.0,
          "watchH": 2590.4
        },
        {
          "title": "[퓨처스리그] 롯데자이언츠 vs 삼성라이온즈 (04.13)",
          "date": "2026.04.14",
          "category": "고정",
          "views": 45238,
          "ctr": 7.93,
          "retention": 3.6,
          "shareRate": 2.23,
          "likeRate": 7.78,
          "subConv": 121.6,
          "watchH": 4076.7
        },
        {
          "title": "[퓨처스리그] 롯데자이언츠 vs 기아타이거즈 (04.24)",
          "date": "2026.04.25",
          "category": "고정",
          "views": 39864,
          "ctr": 6.61,
          "retention": 2.9,
          "shareRate": 1.96,
          "likeRate": 7.53,
          "subConv": 112.9,
          "watchH": 4427.9
        },
        {
          "title": "[퓨처스리그] 롯데자이언츠 vs NC다이노스(04.01)",
          "date": "2026.04.01",
          "category": "고정",
          "views": 54823,
          "ctr": 8.17,
          "retention": 13.7,
          "shareRate": 2.32,
          "likeRate": 8.48,
          "subConv": 111.3,
          "watchH": 5918.8
        },
        {
          "title": "[퓨처스리그] 롯데자이언츠 vs 기아 타이거즈 (05.15)",
          "date": "2026.05.15",
          "category": "고정",
          "views": 43892,
          "ctr": 6.86,
          "retention": 2.6,
          "shareRate": 1.0,
          "likeRate": 6.88,
          "subConv": 109.4,
          "watchH": 3982.7
        },
        {
          "title": "[미야자키 연습경기 생중계] vs 세이부라이온즈(2/22)",
          "date": "2026.02.22",
          "category": "고정",
          "views": 371114,
          "ctr": 15.71,
          "retention": 6.9,
          "shareRate": 0.02,
          "likeRate": 0,
          "subConv": 109.1,
          "watchH": 78262.7
        },
        {
          "title": "[퓨처스리그] 롯데자이언츠 vs 삼성라이온즈 (06.06)",
          "date": "2026.06.06",
          "category": "고정",
          "views": 29363,
          "ctr": 6.12,
          "retention": 2.5,
          "shareRate": 1.53,
          "likeRate": 9.98,
          "subConv": 109.0,
          "watchH": 2227.8
        },
        {
          "title": "[HOTDUG] 개막전 승리✨ 리그 1호 홈런부터 루키의 데뷔전 세이브까지🔥(03.28)",
          "date": "2026.03.29",
          "category": "고정",
          "views": 167907,
          "ctr": 6.28,
          "retention": 51.2,
          "shareRate": 2.47,
          "likeRate": 30.65,
          "subConv": 103.6,
          "watchH": 20019.9
        },
        {
          "title": "[퓨처스리그] 롯데자이언츠 vs KT위즈(03.26)",
          "date": "2026.04.01",
          "category": "고정",
          "views": 50380,
          "ctr": 8.4,
          "retention": 4.1,
          "shareRate": 0.18,
          "likeRate": 0.54,
          "subConv": 99.2,
          "watchH": 5888.7
        },
        {
          "title": "[Playlist] 야수 등장곡+응원가 안무 버전✨ #직관전필수시청",
          "date": "2026.04.09",
          "category": "고정",
          "views": 255242,
          "ctr": 7.41,
          "retention": 24.8,
          "shareRate": 17.72,
          "likeRate": 13.5,
          "subConv": 98.7,
          "watchH": 23775.6
        },
        {
          "title": "[퓨처스리그] 롯데자이언츠 vs KT위즈(03.27)",
          "date": "2026.04.01",
          "category": "고정",
          "views": 29967,
          "ctr": 7.5,
          "retention": 5.0,
          "shareRate": 2.1,
          "likeRate": 9.64,
          "subConv": 96.8,
          "watchH": 3151.8
        },
        {
          "title": "[HIGHLIGHT] 롯데 VS 삼성 (03.28) | 개막전 승리🔥",
          "date": "2026.03.28",
          "category": "고정",
          "views": 193420,
          "ctr": 6.79,
          "retention": 44.7,
          "shareRate": 1.72,
          "likeRate": 22.85,
          "subConv": 95.6,
          "watchH": 25736.2
        },
        {
          "title": "[퓨처스리그] 롯데자이언츠 vs 한화 이글스 (05.08)",
          "date": "2026.05.08",
          "category": "고정",
          "views": 60868,
          "ctr": 7.67,
          "retention": 3.0,
          "shareRate": 1.2,
          "likeRate": 7.48,
          "subConv": 95.3,
          "watchH": 5730.9
        },
        {
          "title": "[미야자키 연습경기] vs SSG (3/3)",
          "date": "2026.03.03",
          "category": "고정",
          "views": 245924,
          "ctr": 14.92,
          "retention": 6.9,
          "shareRate": 0.02,
          "likeRate": 0,
          "subConv": 95.2,
          "watchH": 52362.6
        }
      ],
      "watchH": [
        {
          "title": "[미야자키 구춘리그] vs 지바롯데마린스 (3/1)",
          "date": "2026.03.01",
          "category": "고정",
          "views": 292968,
          "ctr": 14.08,
          "retention": 8.7,
          "shareRate": 0.01,
          "likeRate": 0,
          "subConv": 75.1,
          "watchH": 91274.5
        },
        {
          "title": "[미야자키 연습경기 생중계] vs 세이부라이온즈(2/22)",
          "date": "2026.02.22",
          "category": "고정",
          "views": 371114,
          "ctr": 15.71,
          "retention": 6.9,
          "shareRate": 0.02,
          "likeRate": 0,
          "subConv": 109.1,
          "watchH": 78262.7
        },
        {
          "title": "[미야자키 연습경기] vs SSG (3/3)",
          "date": "2026.03.03",
          "category": "고정",
          "views": 245924,
          "ctr": 14.92,
          "retention": 6.9,
          "shareRate": 0.02,
          "likeRate": 0,
          "subConv": 95.2,
          "watchH": 52362.6
        },
        {
          "title": "[미야자키 연습경기 생중계] vs 요미우리자이언츠(2/23)",
          "date": "2026.02.23",
          "category": "고정",
          "views": 236768,
          "ctr": 15.89,
          "retention": 6.6,
          "shareRate": 0.01,
          "likeRate": 0,
          "subConv": 68.4,
          "watchH": 48930.2
        },
        {
          "title": "[Playlist] 2026 롯데자이언츠 팀 응원가 + 신규 응원가 포함! #직관전필수시청",
          "date": "2026.03.28",
          "category": "고정",
          "views": 330669,
          "ctr": 8.14,
          "retention": 19.5,
          "shareRate": 13.65,
          "likeRate": 15.86,
          "subConv": 74.1,
          "watchH": 47870.2
        },
        {
          "title": "[미야자키 구춘리그] vs 두산베어스(2/26)",
          "date": "2026.02.26",
          "category": "고정",
          "views": 228065,
          "ctr": 15.92,
          "retention": 9.8,
          "shareRate": 0,
          "likeRate": 0,
          "subConv": 53.1,
          "watchH": 28052.1
        },
        {
          "title": "[HIGHLIGHT] 롯데 VS SSG (05.02) | 나균안 7이닝 호투 & 6회 타선 폭발! SSG전 위닝 시리즈 확정⚾",
          "date": "2026.05.02",
          "category": "고정",
          "views": 181646,
          "ctr": 8.15,
          "retention": 58.7,
          "shareRate": 0.79,
          "likeRate": 15.77,
          "subConv": 44.0,
          "watchH": 27649.2
        },
        {
          "title": "[HIGHLIGHT] 롯데 VS KT (05.06) | 제대로 불붙은 타선의 화력!",
          "date": "2026.05.06",
          "category": "고정",
          "views": 175346,
          "ctr": 8.19,
          "retention": 57.1,
          "shareRate": 1.0,
          "likeRate": 18.6,
          "subConv": 33.1,
          "watchH": 25768.0
        },
        {
          "title": "[HIGHLIGHT] 롯데 VS 삼성 (03.28) | 개막전 승리🔥",
          "date": "2026.03.28",
          "category": "고정",
          "views": 193420,
          "ctr": 6.79,
          "retention": 44.7,
          "shareRate": 1.72,
          "likeRate": 22.85,
          "subConv": 95.6,
          "watchH": 25736.2
        },
        {
          "title": "[HIGHLIGHT] 롯데 VS 한화(05.19) | 전민재·한동희 홈런포 & 거침없는 주루 플레이!🔥",
          "date": "2026.05.19",
          "category": "고정",
          "views": 153716,
          "ctr": 6.92,
          "retention": 57.1,
          "shareRate": 0.9,
          "likeRate": 17.9,
          "subConv": 46.8,
          "watchH": 23838.9
        },
        {
          "title": "[Playlist] 야수 등장곡+응원가 안무 버전✨ #직관전필수시청",
          "date": "2026.04.09",
          "category": "고정",
          "views": 255242,
          "ctr": 7.41,
          "retention": 24.8,
          "shareRate": 17.72,
          "likeRate": 13.5,
          "subConv": 98.7,
          "watchH": 23775.6
        },
        {
          "title": "[HIGHLIGHT] 롯데 VS SSG (05.01) | 6회 초 & 10회 초의 빅이닝으로 만든 승리!🔥",
          "date": "2026.05.01",
          "category": "고정",
          "views": 144263,
          "ctr": 7.24,
          "retention": 51.3,
          "shareRate": 0.79,
          "likeRate": 16.18,
          "subConv": 40.9,
          "watchH": 23349.4
        },
        {
          "title": "[HIGHLIGHT] KIA vs 롯데 (05.10) | 박세웅의 호투와 차곡차곡 쌓아 올린 점수로 거둔 승리!",
          "date": "2026.05.10",
          "category": "고정",
          "views": 155145,
          "ctr": 7.09,
          "retention": 54.0,
          "shareRate": 0.68,
          "likeRate": 14.38,
          "subConv": 28.4,
          "watchH": 21670.7
        },
        {
          "title": "[AIM HIGH] 청백전 1차전 in 타이난🔥 #하이라이트",
          "date": "2026.02.10",
          "category": "기획",
          "views": 168828,
          "ctr": 6.5,
          "retention": 45.3,
          "shareRate": 0.02,
          "likeRate": 0.02,
          "subConv": 43.2,
          "watchH": 20729.4
        },
        {
          "title": "[HOTDUG] 개막전 승리✨ 리그 1호 홈런부터 루키의 데뷔전 세이브까지🔥(03.28)",
          "date": "2026.03.29",
          "category": "고정",
          "views": 167907,
          "ctr": 6.28,
          "retention": 51.2,
          "shareRate": 2.47,
          "likeRate": 30.65,
          "subConv": 103.6,
          "watchH": 20019.9
        },
        {
          "title": "[HIGHLIGHT] 롯데 VS KT (04.08) | 김진욱의 도미넌트 스타트🔥",
          "date": "2026.04.08",
          "category": "고정",
          "views": 172920,
          "ctr": 5.6,
          "retention": 53.0,
          "shareRate": 1.54,
          "likeRate": 22.96,
          "subConv": 46.8,
          "watchH": 19997.4
        },
        {
          "title": "[HOTDUG] 사직야구장을 열광의 도가니로 만든 김진욱의 8이닝 투구🔥와 김민성의 한 방✨(04.08)",
          "date": "2026.04.09",
          "category": "고정",
          "views": 161864,
          "ctr": 7.28,
          "retention": 48.7,
          "shareRate": 2.32,
          "likeRate": 28.44,
          "subConv": 51.9,
          "watchH": 19875.4
        },
        {
          "title": "사직에서의 청백전! 루키의 호수비와 센터를 가르는 홈런포까지! l 1, 2군 합동 청백전 H/L",
          "date": "2026.03.10",
          "category": "기획",
          "views": 151851,
          "ctr": 7.21,
          "retention": 43.8,
          "shareRate": 0.01,
          "likeRate": 0.08,
          "subConv": 27.7,
          "watchH": 19522.6
        },
        {
          "title": "[HIGHLIGHT] 롯데 VS LG (04.15) 빈틈없는 무실점 릴레이와 응집력으로 일궈낸 승리!",
          "date": "2026.04.15",
          "category": "고정",
          "views": 163253,
          "ctr": 7.56,
          "retention": 55.8,
          "shareRate": 1.27,
          "likeRate": 20.81,
          "subConv": 57.0,
          "watchH": 18869.1
        },
        {
          "title": "[HOTDUG] 개막 2연승을 이끈 4개의 홈런🔥 더그아웃에 도파민이 팡팡 터져버렸다✨(03.29)",
          "date": "2026.03.30",
          "category": "고정",
          "views": 170656,
          "ctr": 7.61,
          "retention": 53.9,
          "shareRate": 2.22,
          "likeRate": 27.05,
          "subConv": 87.3,
          "watchH": 18727.0
        }
      ]
    }
  },
  "traffic": {
    "cur": {
      "label": "2026 1~6월",
      "data": [
        {
          "source": "탐색 기능",
          "views": 11329161,
          "ctr": 8.34,
          "pct": 40.1
        },
        {
          "source": "Shorts 피드",
          "views": 8272458,
          "ctr": 0.0,
          "pct": 29.3
        },
        {
          "source": "추천 동영상",
          "views": 2389275,
          "ctr": 4.52,
          "pct": 8.5
        },
        {
          "source": "채널 페이지",
          "views": 2335270,
          "ctr": 5.0,
          "pct": 8.3
        },
        {
          "source": "YouTube 검색",
          "views": 2013424,
          "ctr": 7.7,
          "pct": 7.1
        },
        {
          "source": "알림",
          "views": 552039,
          "ctr": 0.0,
          "pct": 2.0
        },
        {
          "source": "외부",
          "views": 332097,
          "ctr": 0.0,
          "pct": 1.2
        },
        {
          "source": "직접 입력 또는 알 수 없음",
          "views": 329014,
          "ctr": 0.0,
          "pct": 1.2
        },
        {
          "source": "기타 YouTube 기능",
          "views": 302291,
          "ctr": 0.0,
          "pct": 1.1
        },
        {
          "source": "재생목록",
          "views": 296430,
          "ctr": 5.39,
          "pct": 1.0
        },
        {
          "source": "최종 화면",
          "views": 89553,
          "ctr": 0.0,
          "pct": 0.3
        },
        {
          "source": "관련 Shorts 동영상",
          "views": 8928,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "세로형 실시간 피드",
          "views": 4704,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "해시태그 페이지",
          "views": 1616,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "사운드 페이지",
          "views": 858,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "리믹스 동영상",
          "views": 5,
          "ctr": 0.0,
          "pct": 0.0
        }
      ]
    },
    "prev": {
      "label": "2025 1~6월",
      "data": [
        {
          "source": "탐색 기능",
          "views": 13581662,
          "ctr": 8.38,
          "pct": 41.6
        },
        {
          "source": "Shorts 피드",
          "views": 6987605,
          "ctr": 0.0,
          "pct": 21.4
        },
        {
          "source": "채널 페이지",
          "views": 3629758,
          "ctr": 4.82,
          "pct": 11.1
        },
        {
          "source": "추천 동영상",
          "views": 3113227,
          "ctr": 4.02,
          "pct": 9.5
        },
        {
          "source": "YouTube 검색",
          "views": 3052496,
          "ctr": 8.53,
          "pct": 9.3
        },
        {
          "source": "알림",
          "views": 618318,
          "ctr": 0.0,
          "pct": 1.9
        },
        {
          "source": "외부",
          "views": 423669,
          "ctr": 0.0,
          "pct": 1.3
        },
        {
          "source": "기타 YouTube 기능",
          "views": 401707,
          "ctr": 0.0,
          "pct": 1.2
        },
        {
          "source": "직접 입력 또는 알 수 없음",
          "views": 375822,
          "ctr": 0.0,
          "pct": 1.2
        },
        {
          "source": "최종 화면",
          "views": 359154,
          "ctr": 0.0,
          "pct": 1.1
        },
        {
          "source": "재생목록",
          "views": 61820,
          "ctr": 6.29,
          "pct": 0.2
        },
        {
          "source": "관련 Shorts 동영상",
          "views": 30539,
          "ctr": 0.0,
          "pct": 0.1
        },
        {
          "source": "세로형 실시간 피드",
          "views": 25908,
          "ctr": 0.0,
          "pct": 0.1
        },
        {
          "source": "해시태그 페이지",
          "views": 4623,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "사운드 페이지",
          "views": 717,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "동영상 카드 및 특수효과",
          "views": 207,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "리믹스 동영상",
          "views": 10,
          "ctr": 0.0,
          "pct": 0.0
        }
      ]
    }
  },
  "daily": {
    "ctr": [],
    "likes": []
  }
};
